sinatra/sinatra

lib/sinatra/base.rb

This was sent to @rkh in a private email over a month ago, but since the security issue is minor, I haven't received any feedback from @rkh other than acknowledgement of receipt of the email, and this doesn't appear to have been addressed, I thought it best to post the fix publicly here.  Below is my email to @rkh:
```
Subject: Minor Security Vulnerability in Sinatra Development Mode
Konstantin,
This is a really minor security issue with sinatra that I found.
In development mode, Sinatra adds support for displaying the "Sinatra
doesn't know this ditty" 404 page.  This links to a picture, which
Sinatra also handles via:
https://github.com/sinatra/sinatra/blob/master/lib/sinatra/base.rb#L1908
get '/__sinatra__/:image.png' do
filename = File.dirname(__FILE__) + …
```

Fix access to arbitrary .png files in ruby 1.8 development mode

---

test/rdoc_test.rb

https://github.com/rdoc/rdoc/pull/329 changed page-top link from `documentation` to `top`.
Since we rely on both the rdoc gem and bundled versions, add regex to allow both documentation or top in the result string.

Fix rdoc page-top link matching

---

README.ru.md

Reference: #903
Convert symbols params to string for all `params` and `session` variables in Russian README.
/cc @kgrz and @kytrinyx

Convert params hash symbols to strings - Russian

---

README.hu.md
README.ko.md
README.zh.md

Reference: #903
Convert symbols params to string for all `params` and `session` variables in `.hu`, `.ko` and `zh` README files
/cc @kgrz and @kytrinyx

Convert params hash symbols to strings - final

---

README.de.md
README.es.md
README.fr.md
README.hu.md
README.ja.md
README.ko.md
README.md
README.pt-br.md
README.pt-pt.md
README.ru.md
README.zh.md

Complete #917
Change `^` and `$` regexp pattern matches to `\A` and `\z` respectively in all readme files.
Also added a comment to the other regex example (in russian readme) like as in #947 PR.
/cc @kytrinyx

Safer regexp in route matching examples

---

lib/sinatra.rb

As `require 'sinatra/base'` is the first line of sinatra/main.rb, this looks redundant to me.

remove a redundant `require`

---

lib/sinatra/base.rb

the handling of path separators at the end is simplified.

refactor Base.compile

---

README.md

Issue: https://github.com/sinatra/sinatra/issues/941
Discussion: https://github.com/sinatra/sinatra/issues/937
Although threading depends on the underlying Rack handler, the absence
of any mention of multi-threaded mode/concurrency seems to confuse users
and it was decided to add some pointers to clarify this.

Add documentation for Multithreaded modes

---

README.md

It's hard to find Sinatra channel because https://sinatra-slack.herokuapp.com has only an invitation link.

Added a link to Slack in README

---

lib/sinatra/base.rb

Hello,
Just for reference, the methods of Array #[] and #[]= are faster than #pop and #<<, and after this refactoring, you no longer need to invoke #<< or #[]= in normal case .
*Thank you for your great tool and its continuous development

refactor Base.compile: modified the handling of special cases

---

lib/sinatra/base.rb
test/public/hello+world.txt
test/static_test.rb

Hello there,
I encountered issues with + signs in the URLS for static files. The issue has been discussed in #1004 and #463 but the patch applied after these has not been made available to static files URLs.
I just changed the unescape method to be used to be the new one and added 2 unit tests regarding + signs in the URLs.
Regards,

Use the URI_INSTANCE.unescape method in static files paths resolution

---

lib/sinatra/base.rb

* Revert special char in heredoc fix specific to 1.9.2
This reverts commit 3c99033fcc34d6a231466e01c6f60fb4be9e8bfb. It was made to
avoid a syntax error on Ruby 1.9.2. A tick in a heredoc now doesn't raise an
error under Ruby 2.2.0.
* Remove check for availability of URI::Parser
Related Commit: 4a02a757fde29ba21d241c838c8114f64a393fae
In the above commit, the URI parser instance was switched based on the
availability of the `Parser` module because Ruby 1.9.2 and above deprecated
the usage of URI::decode in favour of URI::Parser#unescape. This change
removes this switch since this is not required anymore.
* Use `singleton_class` in lieu of class << self whereever applicable
* Remove 1.8 specific handling in `time_for`
Ruby 1.8 didn't support `to_time` method on a Time object, and so there …

Remove some 1.9.x 1.8.x specific workarounds 

---

CHANGELOG.md
CONTRIBUTING.md
Rakefile

My first ruby project PR :tada: 
* moved `CHANGES` to `CHANGELOG.md`
* updated `CONTRIBUTING.md` doc 
* updated Rakefile to use `CHANGELOG.md`.
original issue: 
https://github.com/sinatra/sinatra/issues/1042

change CHANGES to CHANGELOG.md 

---

lib/sinatra/base.rb

The Helper module was using explicit methods to delegate `session` and `logger` to `request`. By extending it with Forwardable, this is now done the proper way i.e. using Ruby's delegation methods.

extended Helper with Forwardable for delegation

---

lib/sinatra/base.rb

Hi,  I noticed the original code ```char.tr('A-Z', 'a-z') ``` was to downcase the capital letter ， So why not just use ```String#downcase``` method?

simplify compile method's code

---

lib/sinatra/show_exceptions.rb

While using sinatra with a Rails 5 application, I was using rack 2.0.0.alpha. It appears that Rack changed the file name which lead to some debugging. I've made it the default for sinatra to require `'rack/show_exceptions'` and if it fails, falls back to `'rack/showexceptions'`.

Rack 2 Support

---

lib/sinatra/base.rb
test/helpers_test.rb

* `Rack::File#serving` now returns `Rack::File::Iterator`. Use that to figure
out if the 'Content-Length' field should be deleted or not inside the `body()`
helper.
* The API of `Rack::File#serving` has been changed to take two arguments:
`request` and `path` of the file. `Rack::File` would then interpret the file
path based on the root path supplied to it's `#new` method, and the `path`
value passed into the `#serving` method.
* Set the root path for `Rack::File` to the app root path.
* Revert the earlier change to use `Rack::File#call` method because it appends
the route path fragment to the root path provided to `Rack::File#new` and
considers that as the file path for the static file.  Also, it doesn't work
with POST requests of static files, which Sinatra does. So we can't quite use …

Revert back to Rack::File#serving; use new API

---

README.es.md
README.fr.md
README.hu.md
README.ja.md
README.ko.md
README.md
README.pt-br.md
README.pt-pt.md
README.ru.md
README.zh.md

This will generate a linked representation for all
`http://localhost:4567` URLs in the README.
I've noticed some PRs in the `sinatra/sinatra.github.com` repo (for
example: 3e5ac47e73d80da584e08a23b47b0867dab0c91b) were opened to add
anchor tags around the localhost URL. However, directly modifying data
in `_includes` in that repo won't be useful because those files are
auto-generated periodically. They should be changed here.

Change localhost links to linked representation

---

README.md

The original example would also match `GET /posts_anything` as `GET /posts` with a format of `"_anything"` because of the optional format separator, forcing the separator is kind of an ugly example so switch to using a trailing slash which should be recognised either way (I think). It'd be nice to be able to create optional groups e.g. `(.:format)?`

Update README to flag issue with optional routes.

---

.travis.yml
Gemfile
README.md
lib/sinatra/base.rb
lib/sinatra/show_exceptions.rb
lib/sinatra/version.rb
sinatra.gemspec
test/helper.rb
test/helpers_test.rb
test/routing_test.rb
test/settings_test.rb

(Reopening #1029 as a branch on core project to allow collaborator activity)
(Holy crap I named the branch with "2.2.0" but I'm not switching it around again. Sorry!)
Here we go!
The Plan:
- Drop support for Rubies earlier than 2.2 (MRI and equivalent implementations)
- Change nothing else
- Move 1.4 development to the `1.4.x` branch, where releases will come from until 2.0 is fully released
Tasks:

Sinatra 2.0.0 alpha [redux]

---

lib/sinatra/base.rb
test/routing_test.rb

This is kind of ugly, but I couldn't see a better way.  One
potential issue is that the splat and captures route params
will be overwritten by the error handler.  There's no way to
change that without breaking backwards compatibility.  We
could potentially offer the route splat/captures under
different param names, though.

Make route params available during error handler (Fixes #860)

---

lib/sinatra/base.rb
test/routing_test.rb

This makes not_found just call error 404, instead of also handling
the Sinatra::NotFound specially.

Unify not_found and error 404 behavior (Fixes #814)

---

lib/sinatra/base.rb
lib/sinatra/show_exceptions.rb

Hello!
[`'literal'.freeze'` fever](https://github.com/rack/rack/pull/737) not affected Sinatra and it's cool because now we have a better option: `frozen_string_literal` pragma introduced in Ruby 2.3.0!

Enable frozen_string_literal feature.

---

CHANGELOG.md

This way, services like https://allmychanges.com will be easier to parse file. And GitHub will render it properly.

Make proper Markdown headers in the CHANGELOG.md

---

lib/sinatra/base.rb

The documentation gives an incorrect example of the `Cache-Control` response header keyword: the transformation should be `:s_maxage => 's-maxage'`, not `:s_max_age => 's-max-age'`. Please see [Section 14.9 of RFC2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.9) for more information. Additionally, the method does a `#to_i` on `:maxage`, so it should probably do a `#to_i` on `:s_maxage` as well. This patch resolves both issues.

Fix s-maxage and value coercion

---

.travis.yml
Gemfile
lib/sinatra/base.rb
sinatra.gemspec
test/compile_test.rb
test/helper.rb
test/routing_test.rb

This PR makes Sinatra use [Mustermann](https://github.com/rkh/mustermann/blob/master/mustermann/README.md). It also updates the pattern to what I'd like the [Sinatra 2.0 syntax](https://github.com/rkh/mustermann/blob/master/mustermann/README.md#-sinatra-pattern) to be, it is generally compatible with [the old syntax](https://github.com/rkh/mustermann/blob/master/mustermann-simple/README.md).
This will also lead to more meaningful errors on broken patterns.
Advanced Mustermann features are not yet exposed.

Use Mustermann for patterns

---

Gemfile
sinatra.gemspec

Various tests aren't executed on travis ci since we supported the reel.
The test result of [Add Reel support. ](https://travis-ci.org/sinatra/sinatra/jobs/106012045)
```
575 runs, 906 assertions, 0 failures, 0 errors, 0 skips
```
Previous test result https://travis-ci.org/sinatra/sinatra/jobs/106007160
```
1083 runs, 2376 assertions, 0 failures, 0 errors, 0 skips
```
So, I fixed the issue by disabling reel as default web server. Thoughts?

Lock celluloid 0.16.0 and fix rack version

---

lib/sinatra/base.rb

I noticed a faulty regexp in Sinatra's uri():
The regexp /[A-z]/ matches all alphabets, but also six non-alphabetic characters, as demonstrated by ("A".."z").to_a.join
=> "ABCDEFGHIJKLMNOPQRSTUVWXYZ[\\]^_`abcdefghijklmnopqrstuvwxyz"

Fix regexp to use case-insensitivity correctly

---

lib/sinatra/base.rb

Let the `status` helper accept symbols representing HTTP status codes, by looking up the numeric status code in `Rack::Utils`
This allows you to e.g. specify `status :accepted` instead of `status 202`, so readers of your code doesn't have to remember less used status codes.

Allow status to be specified with symbols

---

lib/sinatra/base.rb

The change above makes sure that the `default_content_type` option is always deleted from the options.
This in turn makes sure that identical template is cached only once, regardless of whether the explicit `content_type` option is specified or not.
Not to mention it also makes sure that the `default_content_type` option is not passed as an engine option to the engine which might complain about it.

Fix duplicate caching of some templates

---

lib/sinatra/base.rb
test/helpers_test.rb
test/request_test.rb
test/routing_test.rb

Requests that raise errors when parsing query parameters will now respond with a 400 status instead of 500 as suggested by the Rack [docs](http://www.rubydoc.info/github/rack/rack/master/Rack%2FQueryParser%3Aparse_nested_query). Fixes #1058. See #1058 for steps to reproduce.
Exceptions caused by parsing bad parameters were raised outside of the `dispatch!` method so the default exception handler was not invoked. That is why these exceptions bubbled up to the app server and exception messages were being displayed in the browser.

Add error handling for requests with invalid params (Fixes #1058)

---

README.md
test/routing_test.rb

Related to #1107 
The router treats paths with trailing slashes different from the ones without. 
Add tests for this and also mention it in the README.
Following @zzak's [comment](https://github.com/sinatra/sinatra/issues/1107#issuecomment-217849114).

Add tests for trailing slashes in the path

---

lib/sinatra/base.rb

The recent upgrade of rack-protect brought in some new backwards-incompatible
defaults. Notably, they break the Sidekiq web UI (see mperham/sidekiq#3070),
and could have a similar impact broadly. This should restore enough access
to get Sidekiq et al. (mostly) working.

Restore some CSP defaults

---

sinatra-contrib/lib/sinatra/content_for.rb

Update `content_for` docs pointing to the issue about nested templates.
Close https://github.com/sinatra/sinatra/issues/1143.

Update content_for docs

---

README.md
lib/sinatra/base.rb
test/settings_test.rb

By setting the session middleware as an option, rack protection for
sessions will be enabled by default and other session settings will be
applied to the middleware. Fixes #1038.
Example:
```
set :sessions, :session_store => Rack::Session::Pool, :expire_after => 2592000
```

Add option to set the session middleware when enabling sessions

---

rack-protection/lib/rack/protection/authenticity_token.rb
rack-protection/spec/lib/rack/protection/authenticity_token_spec.rb
rack-protection/spec/lib/rack/protection/form_token_spec.rb
rack-protection/spec/lib/rack/protection/remote_token_spec.rb

Replaces sinatra/rack-protection/pull/115.
@zzak so instead of adding a new utility module, I just added the class methods to `AuthenticityToken`. I wasn't able to make use of the `#random_string` method because it doesn't allow the length to be set and it doesn't return a base64 encoded value.
Let me know if you have any more suggestions to clean this up. Thanks!

Mitigate BREACH attack

---

README.de.md
README.es.md
README.fr.md
README.hu.md
README.ja.md
README.ko.md
README.md
README.pt-br.md
README.pt-pt.md
README.ru.md
README.zh.md
lib/sinatra/base.rb
test/helper.rb
test/integration_helper.rb

`RACK_ENV` should not be used with values other than `development` and `deployment`. Therefore, it can't be used to check for `production environment.
See http://www.hezmatt.org/~mpalmer/blog/2013/10/13/rack_env-its-not-for-you.html
In fact, it can even cause some issues if your app is using unicorn, as they're including internal rack middlewares relying on `RACK_ENV` to have the `deployment` value.
See https://github.com/defunkt/unicorn/blob/master/lib/unicorn.rb#L56-L79
Rack itself does that too.
https://github.com/rack/rack/blob/4e4ab39b0508aa3e59f5d7e53696ef6ae7c220ed/lib/rack/server.rb#L228
This removes using `RACK_ENV`, and replaces it with `SINATRA_ENV`.
Since it's a major changes, it should be merged in the Sinatra 2.0 branch. I'm not seeing anything of the kind, so feel free to …

Introduce APP_ENV and remove RACK_ENV

---

lib/sinatra/base.rb

Here's a fix for Ruby 2.4 warnings.
Note that this patch slightly changes the behavior.
The previous code was ignoring Bignum values both in `invoke()` and `set()`.
But I suppose that was not intentional.

⚠️ constant ::Fixnum is deprecated

---

CHANGELOG.md
lib/sinatra/base.rb
test/server_test.rb

Fix for #1205, with test and changelog entry.

Initialize middleware before first request, as is the case with direct Rack usage. Fixes #1205

---

Gemfile
rack-protection/lib/rack/protection/content_security_policy.rb
rack-protection/spec/lib/rack/protection/content_security_policy_spec.rb

Issue #1201 Modernizes Rack::Protection::ContentSecurityPolicy to support current CSP2 and CSP3 directives.
Issue #1200 Fixes a minor security warning on `bundle install` in a fresh repo.
Removes inline docs which were incomplete and insufficient for what is now
quite complex in CSP2 and CSP3. Adds additional current links to excellent
doc resources and tools.

Modernize Rack::Protection::ContentSecurityPolicy

---

lib/sinatra/base.rb
lib/sinatra/show_exceptions.rb
test/helpers_test.rb
test/routing_test.rb
test/settings_test.rb

This patch prevents exceptions that respond to #http_status with 400 from bypassing/breaking show_exceptions, raise_errors, and error handlers.

Improve BadRequest logic. Partially reverts 8f8df53, fixes #1211

---

rack-protection/lib/rack/protection/strict_transport.rb
rack-protection/spec/lib/rack/protection/strict_transport_spec.rb

The preload option allows the domain to be included in browsers HSTS preload list. See https://hstspreload.appspot.com/

Adds preload option to Rack:Protection:StrictTransport

---

.gitignore
Gemfile
Rakefile
test/helper.rb

Right now the test:coverage task is expecting to use rcov, so I've updated it to use simplecov instead. Hopefully that's helpful.
As a follow up I could look into sending the coverage info to codeclimate or coveralls as part of the CI build.

Updated test:coverage rake task to use simplecov

---

lib/sinatra/base.rb

JRuby-9.1.0 seems to fix [this problem](https://github.com/jruby/jruby/issues/1285).

Drop symbolization in #generate_method

---

rack-protection/lib/rack/protection/authenticity_token.rb
rack-protection/lib/rack/protection/form_token.rb
rack-protection/lib/rack/protection/remote_token.rb
rack-protection/spec/lib/rack/protection/authenticity_token_spec.rb
rack-protection/spec/lib/rack/protection/form_token_spec.rb
rack-protection/spec/lib/rack/protection/remote_token_spec.rb

Adds a new configurable option `:csrf_key` that allows the csrf session key to be configured to be shared with other frameworks. 
For instance it could be changed to `:_csrf_token` to be compatible with Rails. This way Sinatra forms could be sent to Rails actions and pass CSRF protection and vice versa (as long as the session is shared).
`use Rack::Protection, :csrf_key => :_csrf_token`
@zzak let me know if you think any option names or method names need changed. I also tried to reduce the public API a bit in this update.

Make authenticity token length a fixed value

---

sinatra-contrib/spec/config_file_spec.rb

I removed deprication warnings that:
```
Deprecation Warnings:
Using `should` from rspec-expectations' old `:should` syntax without explicitly enabling the syntax is deprecated. Use the new `:expect` syntax or explicitly enable `:should` with `config.expect_with(:rspec) { |c| c.syntax = :should }` instead. Called from /Users/shota-iguchi/workspace/sinatra/sinatra-contrib/spec/config_file_spec.rb:27:in `block (2 levels) in <top (required)>'.
```

Make to use `expect` clause instead of `should` for rspec expectations

---

test/helpers_test.rb
test/routing_test.rb
test/settings_test.rb
test/static_test.rb

Fix warnings `Use assert_nil if expecting nil from ...`

---

sinatra-contrib/Gemfile

https://github.com/sinatra/sinatra/pull/1225#issuecomment-269749927
Now, sinatra-contrib  spec is still failing.
I remove `Gemfile.lock` and run `bundle exec rake`, then occured fails from:
```rb
Tilt[:mediawiki]
```
So, I fixed twitter-text gem version using sinatra-contrib same as sinatra Gemfile.
cf: cf2a240a43fcaffb35e3b8b427558e0a84e378d3
it will passes all tests.

Fixed twitter-text version to 1.14.0

---

lib/sinatra/base.rb
sinatra-contrib/lib/sinatra/respond_with.rb
sinatra-contrib/lib/sinatra/streaming.rb

I got some uninitialized instance variable warnings when I ran `RUBYOPT="-w" bundle exec rake` at under sinatra-contrib.
This pull-request fixes that warnings.

Fix uninitialized instance variable warnings

---

lib/sinatra/base.rb

Currently there is a surprising or at least undocumented difference in the behavior of modular and classic style apps: cookies are not signed for classic style applications in development mode, while for modular applications they are always signed, regardless of the environment.
The patch removes the redefinition of the `session_secret` for classic style applications that caused this behavior.
In case the current behavior is intended, at least the docs should be updated to reflect this. Right now the README generally states (see "Using Sessions"):
> To improve security, the session data in the cookie is signed with a session secret. A random secret is generated for you by Sinatra.
_Short tale of woe: I wanted to create a simple example for cookies and how they work on the HTTP level, and …

Always sign cookies, also in development mode for classic style apps

---

sinatra-contrib/lib/sinatra/cookies.rb
sinatra-contrib/spec/cookies_spec.rb

This adds an explicit `set` method to contrib/cookies which allows you to override the default or application-wide cookie settings.
I was running into an issue where I wanted to set one cookie as HttpOnly, and allow one to be accessible via JavaScript. I didn't see an easy way to do that with the existing `[]=` method. This way, if someone wants to set cookies with different options, they can pass them to the `set` method, and `[]=` is defined in terms of `set`.

Add explicit set method to contrib/cookies

---

README.de.md
README.md

This part is very specific and probably never used. If you're new to sinatra this shouldn't be kept in the Readme.

remove the roll your own part of docs

---

sinatra-contrib/lib/sinatra/config_file.rb

Fixes #1142 
This patch makes `ConfigFile` output loading info only when `:logger` and `:logging` are enabled.
Maybe, other extensions can also be combined with `Sinatra::CustomLogger`.

avoid logging to stderr when loading config files

---

lib/sinatra/base.rb
test/request_test.rb
test/routing_test.rb

Rebases https://github.com/sinatra/sinatra/pull/1169 by @singpolyma without the docs update, as it's part of the [Sinatra 2.0](https://github.com/sinatra/sinatra/milestone/18) milestone.
From original PR:
> With the old strategy for indifferent access, one still had to use the
> correct one of String or Symbol to ask if params#has_key? -- this fixes
> that so that access is more truly indifferent.

Rebase: Make #has_key? also indifferent in access

---

rack-protection/rack-protection.gemspec

StrictTransport, CookieTossing, and ContentSecurityPolicy were not listed in the gemspec and hence not packaged. Let's use a glob to select middlewares to prevent this from happening in the future!

rack-protection: Use a glob to select middlewares

---

sinatra-contrib/lib/sinatra/namespace.rb
sinatra-contrib/spec/namespace_spec.rb

Fixes #1251 
@mwpastore @zzak Could you confirm this?

avoid executing filters even if prefix matched with other namespace

---

sinatra-contrib/sinatra-contrib.gemspec
sinatra.gemspec

@zzak `< 1.0.0` may be invalid because a few bugs and features hasn't been ported.
I understand what you say?

relax mustermann dependency

---

lib/sinatra/base.rb
lib/sinatra/indifferent_hash.rb
sinatra-contrib/lib/sinatra/config_file.rb
test/indifferent_hash_test.rb
test/request_test.rb

Have you ever been frustrated that `params.has_key?(:sym)` works, but not `params.key?(:sym)`? 
Have you ever tried to use `params.dig(..)` with symbol keys? How about `#fetch` or `#values_at`?
Does this snippet of code make your blood pressure spike?
```ruby
params['foo'] = "hello"
params[:foo] # => "hello"
params['foo'] # => "hello"
params[:bar] = "world"
params[:bar] # => "world"
params['bar'] # => nil # oops!
```
How about the fact that query parameters are mapped to string keys, but Sinatra's internal `captures` parameter is mapped to a symbol key? So even if you commit to using all string keys for params, you may still run into issues. 
Our IndifferentHash implementation is simultaneously too indifferent and not indifferent enough. One might say it is indifferently indifferent! I …

Rage Against the Params

---

lib/sinatra/base.rb
test/routing_test.rb

ref #1107 
I've tried to implement first logic.
This approach is same with [padrino](https://github.com/padrino/padrino-framework/blob/master/padrino-core/lib/padrino-core/path_router/matcher.rb#L24).

add :strict_paths option for managing trailing slashes

---

sinatra-contrib/Rakefile

Rake task `bundle exec rake doc` is failing.
```sh
sinatra/sinatra-contrib git:(master)> be rake doc
writing doc/sinatra-config-file.rdoc
writing doc/sinatra-content-for.rdoc
writing doc/sinatra-cookies.rdoc
writing doc/sinatra-custom-logger.rdoc
rake aborted!
NoMethodError: undefined method `scan' for nil:NilClass
/Users/yuva/clients/opensource/sinatra/sinatra-contrib/Rakefile:16:in `block (3 levels) in <top (required)>'
/Users/yuva/clients/opensource/sinatra/sinatra-contrib/Rakefile:13:in `glob'
/Users/yuva/clients/opensource/sinatra/sinatra-contrib/Rakefile:13:in `block (2 levels) in <top (required)>'
/Users/yuva/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
/Users/yuva/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => doc => doc:all => …
```

[sinatra-contrib] Ignore decompile.rb while generating docs

---

rack-protection/.gitignore
rack-protection/Rakefile

Copied over rake task from `sinatra-contrib`. Part of #1275

[issue-1275] add rake task to generate rack-protection docs, similar to sinatra-contrib

---

test/helper.rb
test/indifferent_hash_test.rb

Though it is small thing, I wonder if "require 'bundler/setup'" is needed in the tests.
Because when I removed the lines in the tests, all the test was passed.
And `bundler/setup` has already been loaded by `bundle` command at least on my local environment.
See below commands.
```
$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
$ bundler -v
Bundler version 1.14.6
$ bundle exec ruby -e 'ENV.each {|name, value| puts "#{name}=#{value}" }' | grep RUBYOPT
RUBYOPT=-rbundler/setup
```

Remove a line for "require 'bundler/setup'".

---

rack-protection/rack-protection.gemspec

Hello,
I want to use RSpec 3 latest version for rack-protection.
The reason why I used `~> 3.6` instead of `~> 3.6.0` is to prevent below warning message.
```
$ gem build rack-protection.gemspec
WARNING:  description and summary are identical
WARNING:  open-ended dependency on rack (>= 0) is not recommended
if rack is semantically versioned, use:
add_runtime_dependency 'rack', '~> 0'
WARNING:  open-ended dependency on rack-test (>= 0, development) is not recommended
if rack-test is semantically versioned, use:
add_development_dependency 'rack-test', '~> 0'
WARNING:  pessimistic dependency on rspec (~> 3.6.0, development) may be overly strict
if rspec is semantically versioned, use:
add_development_dependency 'rspec', '~> 3.6', '>= 3.6.0'
WARNING:  See …
```

Update RSpec 3 for rack-protection to use latest version.

---

Gemfile

Right now `rbx-3` is available. but the test is failed.
https://travis-ci.org/sinatra/sinatra/jobs/249874847
This PR is to check if the `rbx-3` test is succeeded.

Add erubi for rbx test to fix failed tests.

---

sinatra-contrib/spec/respond_with_spec.rb

This PR has a single cleanup change in a spec file: Avoid the local name `p` for a variable.
This change promotes the `p` to the name `path`. ([`Kernel#p`](https://ruby-doc.org/core-2.4.1/Kernel.html#method-i-p) exists, and there's room for the more descriptive name.)

Spec: Rename a local p to path

---

sinatra-contrib/spec/respond_with_spec.rb

This PR changes the spec for `RespondWith` to avoid a Ruby warning by getting rid of unused code.
- the "provides" method was never called, and its instance variable never set
- this change removes warnings output from the test run

Spec: Drop unused local assistance method "provides"

---

sinatra.gemspec

In order to support local unpacking, this PR adds `VERSION` to the files list in the gemspec.
- Fixes #1308

Add VERSION file to gemspec

---

.gitignore
sinatra-contrib/lib/sinatra/engine_tracking.rb
sinatra-contrib/lib/sinatra/test_helpers.rb

This PR documents the `Sinatra::TestHelpers` module and `EngineTracking`.
- where I was unsure of how YARD would bring in API docs links, I used hyperlinks
- grouped `def_delegators` methods and labeled the headings
- in order to avoid mistakes checking in the `doc/` directory, I git-ignored it
See #1307

[sinatra-contrib] API docs: TestHelpers, EngineTracking

---

README.md

Documentation of server_settings option for Issue 940. Found a few examples of WEBrick servers using the `set :server_settings` option, and of Thin using a `server_settings` method within a class that inherits from `settings` inside the `configure` call.

Documentation of server_settings option for Issue 940

---

sinatra-contrib/spec/cookies_spec.rb

This PR removes this warning from the test output:
`/home/travis/build/sinatra/sinatra/sinatra-contrib/spec/cookies_spec.rb:415: warning: assigned but unused variable - seen`

Spec: Remove unused local 'seen' to avoid Ruby warning

---

sinatra-contrib/spec/namespace_spec.rb

This PR adds parenthesees around a RegExp literal.
This avoids the warning
> ambiguous first argument; put parentheses or a space even after / operator

Spec: add parentheses to avoid Ruby warning

---

Gemfile
sinatra-contrib/Gemfile

This PR tries to avoid a warning in the spec output by updating a gem dependency to its latest released version.
The [`twitter-text` gem](https://github.com/twitter/twitter-text/commits/master/rb) was locked to v1.14.0 in cf2a240a43fcaffb35e3b8b427558e0a84e378d3 for build failure reasons.
The build now passes. Perhaps things have stabilized?
<details>
The current warning is:
```
/home/travis/.rvm/gems/ruby-2.4.1/gems/twitter-text-1.14.0/lib/twitter-text/regex.rb: warning: character class has duplicated range
/home/travis/.rvm/gems/ruby-2.4.1/gems/twitter-text-1.14.0/lib/twitter-text/regex.rb: warning: character class has duplicated range
/home/travis/.rvm/gems/ruby-2.4.1/gems/twitter-text-1.14.0/lib/twitter-text/regex.rb: warning: character class has duplicated range …
```

Spec: Update gem twitter-text to 1.14.7

---

CHANGELOG.md
lib/sinatra/base.rb
sinatra-contrib/lib/sinatra/runner.rb

This PR fixes a few misspellings.
- renames a private method
- fixes a typo in CHANGELOG
- fixes a typo in a documentation comment

Fix misspellings

---

README.md

From  `[rack-contrib](https://github.com/rack/rack-contrib#readm)`
To `[rack-contrib](https://github.com/rack/rack-contrib#readme)`

Fixed the wrong link in the "Rack Middleware" section of the readme file

---

README.md

* update outdated links
* use https wherever available
* fix Markdown for links
* fix inconsistent indentation in Table of Contents
* wrap long lines to around 80 words

Fix links and Markdown in README

---

lib/sinatra/show_exceptions.rb

This overrides Rack::ShowExceptions::TEMPLATE without affecting other Rack apps that are mounted alongside Sinatra. Resolves #1376. 
I would like to revisit this if rack/rack/pull/1223 gets merged 😜

Override Rack::ShowExceptions#pretty to set custom template

---

lib/sinatra/base.rb
test/routing_test.rb

Make sure `@params` are initialized for an app, so that they exist if processing a request with a custom error handler. Currently if params are invalid an error is raised before `@params` is set, causing a `NoMethodError` for `nil:NilClass` down the chain. Fixes #1350.

Fix issue with custom error handler on bad request

---

lib/sinatra/base.rb
rack-protection/lib/rack/protection/path_traversal.rb

Due to the Windows environment, more check backslashes in `static!` method and enhanced the `path_traversal` validation in `rack-protection`

enhanced path validation in Windows

---

test/sass_test.rb
test/views/hello.sass

Fixed deprecation warning messages that occurred from `rake test` command.
```
DEPRECATION WARNING on line 91 of /Users/shota-iguchi/workspace/sinatra-dev/sinatra/test/sass_test.rb:
Old-style properties like ":background-color white" are deprecated and will be an error in future versions of Sass.
Use "background-color: white" instead.
DEPRECATION WARNING on line 92 of /Users/shota-iguchi/workspace/sinatra-dev/sinatra/test/sass_test.rb:
Old-style properties like ":color black" are deprecated and will be an error in future versions of Sass.
Use "color: black" instead.
.DEPRECATION WARNING on line 24 of /Users/shota-iguchi/workspace/sinatra-dev/sinatra/test/sass_test.rb:
Old-style properties like ":background-color white" are deprecated and will be an error in future versions of Sass.
Use …
```

Remove sass warnings

---

test/sass_test.rb

I removed these warning messages
```
DEPRECATION WARNING on line 66 of /Users/shota-iguchi/workspace/sinatra-dev/sinatra/test/sass_test.rb:
Old-style properties like ":color black" are deprecated and will be an error in future versions of Sass.
Use "color: black" instead.
DEPRECATION WARNING on line 78 of /Users/shota-iguchi/workspace/sinatra-dev/sinatra/test/sass_test.rb:
Old-style properties like ":color black" are deprecated and will be an error in future versions of Sass.
Use "color: black" instead.
```

Remove sass warning messages

---

lib/sinatra/base.rb
test/routing_test.rb

I'm trying to fix #1388 
`params` should be empty hash if requests doesn't matches any regex of routings. But It was returned `{"captures" => []}`. so I fixed to return empty hash object.
```rb
before do
end
get "/" do
params.to_s # returns `{}`
end
```

Fix to ignore empty captures from params

---

lib/sinatra/base.rb

I saw RFC 2616 and RFC 7234(latest...?), response `Cache-Control` min-stale  directive does not exist. So I updated `Cache-Control` docs.

Fix Cache-Control header docs [ci skip]

---

rack-protection/lib/rack/protection/authenticity_token.rb

This PR adds more RDoc to the `AuthenticityToken` class.
It adds the example app provided by @tonytonyjan in https://gist.github.com/tonytonyjan/8a551a9808295287a8c3c43a6ecdaf0e
This PR wants to fix #1165.

[docs] Authenticity Token: example app

---

sinatra-contrib/lib/sinatra/config_file.rb
sinatra-contrib/spec/config_file/with_env_defaults.yml
sinatra-contrib/spec/config_file_spec.rb

Fixes unpredictable behaviour from Sinatra::ConfigFile detailed in https://github.com/sinatra/sinatra/issues/1243.
* Loads settings for the current environment regardless of other environments defined in the configuration file. Previously settings failed for all environments unless all in the file were implemented in the application.
* Removes the restriction that settings can only be inherited from other environments, so that this is possible:
```yaml
default: &default
foo: bar
development:
<<: *default
production:
<<: *default
foo: baz
test:
<<: *default
```
* Amends source documentation to represent new behaviour.
* Includes tests for the new behaviour.
* Backwards compatible with existing settings implementations.

Issue#1243 configurations with unimplemented environments

---

rack-protection/lib/rack/protection/base.rb
rack-protection/spec/lib/rack/protection/protection_spec.rb

Javascript can run in XML by defining an HTML namespace.  Example: `<script xmlns="http://www.w3.org/1999/xhtml">alert(1)</script>`.  Request is adding text/xml and application/xml to :html_types to include protection for these content types.
Example
```
Payload:
http://localhost:4567?example_rxss_param=]]%3E%3Cscript%20xmlns=%22http://www.w3.org/1999/xhtml%22%3Ealert(1)%3C/script%3E%3C![CDATA[
Response:
<![CDATA[]]>
<script xmlns="http://www.w3.org/1999/xhtml">alert(1)</script>
<![CDATA[]>
```

Add xml content-types to valid html_types for Rack::Protection

---

lib/sinatra/base.rb
test/routing_test.rb

Honor the :default_encoding setting for any extracted parameters from the URL.  The force_encoding was scoped to modify only the necessary items for performance.  In the test, be explicit about our dependency on this value.
Fixes #1362.

Encode route parameters using :default_encoding setting

---

sinatra-contrib/sinatra-contrib.gemspec

This fixes broken tests and behaviors.

lock the backports gem to v2.8.2

---

sinatra-contrib/lib/sinatra/required_params.rb
sinatra-contrib/spec/required_params_spec.rb

Currently, when required_params is called in such a way that it expects a key in the params to be a hash, it fails with error
`undefined method has_key?`
when it is not indeed a hash in the params in a request.
Now, it's been ensured that the key can respond to `has_key?` before `has_key?` is called on it.
So,
`required_params :p1, :p2 => [:p3]`
now works properly even if `:p2` turns out not to point to a hash, e. g. if the params hash is
```
{ p1: 2, p2: 3 }
```
it will properly halt with status 400.
A unit test has also been added to `required_params_spec.rb`. It failed before the fix, but now passes.

Fix Sinatra::RequiredParams implementation

---

CHANGELOG.md

This adds clickable links to PRs and Issues for the part of the CHANGELOG document where those point to this GitHub.

CHANGELOG.md with Markdown links

---

README.md

Adds this badge to the top of the readme:
[![Gem Version](https://badge.fury.io/rb/sinatra.svg)](http://badge.fury.io/rb/sinatra)
(I always want to know the current version when adding a new gem to my Gemfile, so I can figure out what requirement to set it to.)
Additionally, if you're up for it, I'd love you to show the SemVer stability of sinatra using this badge:
[![SemVer](https://api.dependabot.com/badges/compatibility_score?dependency-name=sinatra&package-manager=bundler&version-scheme=semver)](https://dependabot.com/compatibility-score.html?dependency-name=sinatra&package-manager=bundler&version-scheme=semver)
I haven't included that one in this PR though, because I thought I'd ask first (I built the tool that creates those badges, so don't want to spam people with them).

Show Gem version in badge on README

---

rack-protection/rack-protection.gemspec
sinatra-contrib/sinatra-contrib.gemspec
sinatra.gemspec

Specifying metadata links in the gemspec replaces specifying them through the Rubygems web UI (which will soon be deprecated).

Add metadata link to gemspec

---

lib/sinatra/base.rb
test/routing_test.rb

This adds tests to make sure named parameters and regex captures are unescaped, and also provides a potential fix for #1443. I'm not familiar enough with Mustermann to know if it should handle unescaping captures.

Unescape regex captures

---

sinatra-contrib/spec/cookies_spec.rb

A regression was fixed in Rspec so the include matcher once again works as expected.
See https://github.com/rspec/rspec-expectations/pull/1073

Revert back to using include matcher

---

sinatra-contrib/lib/sinatra/capture.rb
sinatra-contrib/sinatra-contrib.gemspec

ActiveSupport was being loaded to provide `Object#try`. It's a very large dependency that can monkey patch many core classes, and although the require in `sinatra-contrib` is targeted and doesn't load all of ActiveSupport, once the gem is on the load path some other libraries will opportunistically load more of it.
`Object#try` is only used twice, maybe it's ok to live with a manual check for nil for now? `sinatra-contrib` currently requires ruby 2.2 or better - once the minimum is lifted to 2.3, Object#try will be provided by ruby core.

Drop activesupport dependency from sinatra-contrib

---

lib/sinatra/indifferent_hash.rb
test/helper.rb
test/indifferent_hash_test.rb

* Print warning on Rubies that require monkeypatching only
* Print warning to stderr instead of stdout
* Load ActiveSupport during internal testing only
* Add SINATRA_ACTIVESUPPORT_WARNING opt-out environment variable
First spike at addressing #1476

IndifferentHash monkeypatch warning improvements

---

rack-protection/lib/rack/protection/session_hijacking.rb
rack-protection/spec/lib/rack/protection/session_hijacking_spec.rb

The existing default is inappropriate for any applications that accept websocket connections.
Some browsers (e.g., Safari 12, Chrome 71) don't set the `Accept-Language` header for websocket requests. A mixture of requests with and without this header results in unavailable sessions in websocket handlers. This affects both Sinatra apps and other websocket apps using rack-protection in their middleware stack.
Considering the partial nature ("this will not prevent determined hijacking attempts") of the employed defense mechanism and current proliferation of TLS support on the web, I propose relaxing the defaults (the attached patch) or disabling the middleware altogether (happy to help with that too).
Attaching request dumps for 3 modern browsers retrieved by running `socket = new …

rack-protection: Don't track the Accept-Language header by default

---

lib/sinatra/base.rb
test/middleware_test.rb

avoid FrozenError when params contains frozen value

---

sinatra-contrib/lib/sinatra/capture.rb
sinatra-contrib/lib/sinatra/engine_tracking.rb

Simplify logic for capturing content for the different template engines. Prior complexity may have been due to encoding issues pre Ruby 2.0, but this doesn't seem to be an issue any longer.

Refactor capture method

---

.travis.yml

This PR **updates the CI matrix** to 
- use latest [JRuby 9.2.5.0 - release blog post](https://www.jruby.org/2018/12/06/jruby-9-2-5-0.html)
- add 2.6.0

CI matrix: add 2.6.0, update JRuby to 9.2.5.0

---

lib/sinatra/base.rb
test/settings_test.rb

ignore bundler/inline from callers

---

CHANGELOG.md
lib/sinatra/base.rb
test/routing_test.rb

Fixes https://github.com/sinatra/sinatra/issues/1514

Avoid `TypeError` when params contain a key without a value on Ruby < 2.4

---

.travis.yml

- drop the sudo: false directive which now does nothing
---
This PR updates the CI matrix to use latest JRuby, 9.2.6.0.
[JRuby 9.2.6.0 release blog post](https://www.jruby.org/2019/02/11/jruby-9-2-6-0.html)

CI: Update matrix versions

---

lib/sinatra/base.rb

Since Rack 2 requires Ruby 2.2+, the extra logic for determining string encoding is no longer necessary. Outdated comments were also removed.

Remove unnecessary code for force_encoding

---

lib/sinatra/base.rb
test/middleware_test.rb

The original fixes are #1506 and #1517.
This commit considers `FrozenError` and `TypeEror` for the case.
`Object#dup` has a possibility of raising `TypeError` when ruby <= 2.3 and the receiver is a special const.
What's special const? It depends on the ruby version. Currently, it's defined [here](https://github.com/ruby/ruby/blob/cf781b0871cb8d6b7135fa74d9549ca1cdb2a846/object.c#L355).
In the ruby-2.3.8, it's defined in other place.
To fix this issue, I had an option which is managing the special const mapping in our code, but it's very hard to manage, and there is a possibility of  increasing complexity. . So I would like to handle the issue by `rescue`ing `TypeError` in this case.
What do you think? Any opinions or any ideas?

avoid multiple errors even if `params` contains special values

---

rack-protection/lib/rack/protection/path_traversal.rb
rack-protection/spec/lib/rack/protection/path_traversal_spec.rb

This PR cleans up Ruby 1.8 compatibility code.
Same kind of thing as https://github.com/sinatra/sinatra/pull/1527

[rack-protection] Drop Ruby 1.8 compat code

---

Gemfile
lib/sinatra/base.rb
sinatra-contrib/lib/sinatra/respond_with.rb
sinatra-contrib/sinatra-contrib.gemspec
test/markdown_test.rb
test/static_test.rb

I found out that Sinatra codebase still contains a code for handling both versions of Tilt (1.x and 2.x), however starting from Sinatra 2.0 the minimally required version of Tilt is 2.0 as well.
I've also added `commonmarker` gem because otherwise it triggers warnings during a test run and does not generate tests for this markdown engine.

Remove outdated code for Tilt 1.x versions 

---

lib/sinatra/base.rb
lib/sinatra/main.rb

When setting environment to production from command line, some development configurations were already registered. For instance the development `NotFound` error handler was setup. Command line options are now parsed before environment configurations are run. Resolves #1544.

Fix issue setting environment from command line option

---

.travis.yml
Gemfile
README.md
lib/sinatra/base.rb

Here I try to fix an another warning from tests.
```
cannot load such file -- pandoc-ruby: skipping markdown tests with
Tilt::PandocTemplate
```
`pandoc-ruby` is not defined in Gemfile, so I add it there. This gem has a prerequisite dependency `pandoc` (a CLI application) that can be installed via apt. That's why I update travis.yml to make it available during a test run.
The final step to make it work is to exclude `outvar` from the option's list provided to the template. When `pandoc` application is called with unsupported parameters it stops the execution and returns an error.
```
Unknown option --outvar.
Try pandoc --help for more information.
```
I'm not really sure why `outvar` parameter is defined by default and what it supposed to do. It seems that it was used before by several …

Add pandoc support

---

lib/sinatra/main.rb

fix a regression, closes #1559

---

test/filter_test.rb

According with this [issue](https://github.com/sinatra/sinatra/issues/1567) 
I've added a test.
There is a [PR](https://github.com/sinatra/sinatra/pull/1569) that fix.

Add test where pre filter cannot modify params on certain cases

---

lib/sinatra/base.rb

Hi. I am currently monkey-patching this in my own project, but I think it would be useful for everyone, so I'm submitting this PR.
Add request method and path to the NotFound exception message. This is useful for exception reporting tools.
As an example, this is what Airbrake looks before this change. I can still get the URL but I have to click in to each report. It is very hard to get a nice overview.
And this is what it looks like after:
Let me know what you think!

Add message to NotFound exception

---

sinatra-contrib/lib/sinatra/respond_with.rb

Resolves #1172. This fetches only the string name of the template class instead of loading the template class (if it hasn't already been loaded).

Lookup Tilt class for template engine without loading files

---

lib/sinatra/base.rb

Changes to the @params hash were being lost if routing params were
supplied because the whole hash was being reset after processing the
route. Resolves #1567.

Remove only routing parameters from @params hash

---

lib/sinatra/base.rb

A keyword argument must be passed with `**` annotation in Ruby 3.0.
https://bugs.ruby-lang.org/issues/14183
In Ruby 2.7.0, passing a keyword argument without `**` occurs some warnings like `warning: The last argument is used as the keyword parameter`.
To avoid this warnings, I added `**` annotations for keyword arguments.
ruby2.7.0-preview3

eliminate warnings of keyword parameter for ruby 2.7.0

---

sinatra-contrib/Gemfile
sinatra-contrib/lib/sinatra/capture.rb
sinatra-contrib/lib/sinatra/content_for.rb
sinatra-contrib/lib/sinatra/engine_tracking.rb
sinatra-contrib/lib/sinatra/respond_with.rb
sinatra-contrib/spec/capture_spec.rb
sinatra-contrib/spec/content_for/different_key.hamlit
sinatra-contrib/spec/content_for/footer.hamlit
sinatra-contrib/spec/content_for/layout.hamlit
sinatra-contrib/spec/content_for/multiple_blocks.hamlit
sinatra-contrib/spec/content_for/multiple_yields.hamlit
sinatra-contrib/spec/content_for/parameter_value.hamlit
sinatra-contrib/spec/content_for/passes_values.hamlit
sinatra-contrib/spec/content_for/same_key.hamlit
sinatra-contrib/spec/content_for/takes_values.hamlit
sinatra-contrib/spec/content_for/yield_block.hamlit
sinatra-contrib/spec/content_for_spec.rb

As explained in https://github.com/k0kubun/hamlit/issues/150, sinatra-contrib's `capture` and `yield_content` don't work with hamlit.gem (another implementation of Haml) because they use helpers specific to haml.gem.
Let them stop using haml.gem-specific helpers if :haml engine is not `Tilt::HamlTemplate` (but `Hamlit::Block::Template`). 
Note that hamlit-block plugin is necessary to make sinatra-contrib's `capture` work with Hamlit.

Support capture and content_for with Hamlit

---

.travis.yml
Gemfile

This PR updates the CI matrix to use latest JRuby, **9.2.9.0**.
[JRuby 9.2.9.0 release blog post](https://www.jruby.org/2019/10/30/jruby-9-2-9-0.html)
In order to make the tests run, JRuby must also pull in the ActiveSupport gem, which this PR also does.

CI: Use jruby-9.2.9.0

---

lib/sinatra/indifferent_hash.rb
test/indifferent_hash_test.rb

close https://github.com/sinatra/sinatra/issues/1571
I tested locally:
```
➜  sinatra bundle exec ruby test/indifferent_hash_test.rb
Run options: --seed 9474
...........................
Finished in 0.004303s, 6274.6921 runs/s, 23471.9963 assertions/s.
27 runs, 101 assertions, 0 failures, 0 errors, 0 skips
```

Support ruby 2.6 Hash#merge with multiple arguments

---

rack-protection/lib/rack/protection/content_security_policy.rb
rack-protection/spec/lib/rack/protection/content_security_policy_spec.rb

Many of the CSP3 no-arg directives are multiple words so calling `sub`
only transforms the first "_" to a "-" when we need to transform all of
them to have a valid directive.

Fix content security policy no-arg directives

---

sinatra-contrib/lib/sinatra/namespace.rb
sinatra-contrib/lib/sinatra/reloader.rb
sinatra-contrib/lib/sinatra/respond_with.rb

These were missed in https://github.com/sinatra/sinatra/pull/1581.

Fix additional Ruby 2.7 keyword warnings

---

lib/sinatra/base.rb
test/static_test.rb

This is raising an exception on a production application I am running. This should be fine since `nil` is an acceptable return type of the method.

Handle null byte when serving static files

---

rack-protection/lib/rack/protection.rb
rack-protection/lib/rack/protection/referrer_policy.rb

Hi everyone. I decided to implement the Referrer-Policy header for rack-protection. It's a really simple header with just a string value, more information:
- https://www.w3.org/TR/referrer-policy/
- https://caniuse.com/#search=referrer-policy
I considered making it enabled by default, since it has low risk of breaking the web, but I want your opinion first.
Worth noting is that the default value I picked, "strict-origin-when-cross-origin", does not work in Chrome at the moment. I picked it as it will be the most sensible default in the future, especially if this is enabled by default. See this bug: https://bugs.chromium.org/p/chromium/issues/detail?id=627968

Add Rack::Protection::ReferrerPolicy

---

lib/sinatra/base.rb
test/request_test.rb
test/routing_test.rb

Fixes https://github.com/sinatra/sinatra/issues/1141.
Adds support for parameters when creating new mime types.
Previously, the user could declare a mime type with parameters like this:
```ruby
configure do
mime_type :rss10, 'application/rss+xml; version="http://purl.org/rss/1.0/"'
end
get '/feed', :provides => [:rss10] do
end
```
But the route would 404 when the version was missing from the accept header:
```bash
curl -H 'Accept: application/rss+xml' -I [host]/feed
HTTP/1.1 404 Not Found 
Content-Type: text/html;charset=utf-8
```
This change allows the route to respond, including the more specific parameters in the Content-Type header.
```bash
curl -H 'Accept: application/rss+xml' -I [host]/feed
HTTP/1.1 200 OK 
Content-Type: application/rss+xml; version="http://purl.org/rss/1.0/"
``` …

Support for parameters in mime types.

---

lib/sinatra/base.rb

I removed useless `private` declares.
When `private` was declared, instance methods which are define after that become private-method.
But, not-instance method (classes and modules) objects are able to load from out side of the module.
```rb
require 'sinatra/base'
Sinatra::Request::AcceptEntry # => Success to load
```

Remove useless private clause

---

sinatra-contrib/README.md
sinatra-contrib/lib/sinatra/quiet_logger.rb
sinatra-contrib/spec/quiet_logger_spec.rb

Hi,
I want to add a QuietLogger to sinatra-contrib gem, that is able to exclude some pathes from the access log. This is usefull to silent asset logging, while seeing the relevant requests of your application in log.
To do that, I had to patch the Rack::CommonLogger a little. I hope it was the right location to do that.
Thanks!

add QuietLogger that excludes pathes from Rack::CommonLogger

---

.travis.yml

This PR updates the CI matrix to use latest JRuby, **9.2.11.0**.
[JRuby 9.2.11.0 release blog post](https://www.jruby.org/2020/03/02/jruby-9-2-11-0.html)
Question for reviewer: Perhaps it's time to let JRuby out of the allow_failures jail?

CI: Update to jruby-9.2.11.0

---

.travis.yml
lib/sinatra/base.rb
test/integration_test.rb

Ruby 2.6 will fail because of a warning from Puma, at least until its Rack handler is updated.
See: https://github.com/puma/puma/pull/2189

Update Rack handler call to use kw args

---

sinatra-contrib/lib/sinatra/namespace.rb
sinatra-contrib/spec/namespace_spec.rb

This allows to set render engine options local to a namespace
Fixes #1254

sinatra-namespace: Allow for `set :<engine>`

---

README.md
lib/sinatra/base.rb
test/response_test.rb
test/settings_test.rb

Historically, Sinatra::Response defaults to a text/html Content-Type.
However, in practice, Sinatra immediately clears this attribute after
instantiating a new Sinatra::Response object, so this default is some-
what suspect. Let's break this behavior and have Sinatra::Response
be Content-Type-less by default, and update the tests to reflect this.
Next, let's introduce a new default_content_type setting that will be
applied (instead of text/html) if the Content-Type is not set before the
response is finalized. This will be great for e.g. JSON API developers.
Let's also make it nil-able to indicate that a default Content-Type
should never be applied.
Wherever Sinatra is emitting HTML, e.g. in error pages, force the
Content-Type to text/html.
Finally, clean up the error-handling logic to …

Add default_content_type setting. Fixes #1238

---

Gemfile

Because of https://github.com/rack/rack/commit/98d9cf5834d4e27e34bbaa017cdfc68795763b55,
the support for thin was removed from rack.

replace thin with puma

---

rack-protection/lib/rack/protection/http_origin.rb
rack-protection/spec/lib/rack/protection/http_origin_spec.rb

- Added `permitted_origin` in lieu of `origin_whitelist`
- Deprecated `origin_whitelist` with a warning
Closes https://github.com/sinatra/sinatra/issues/1620

Replace origin_whitelist with permitted_origins

---

rack-protection/lib/rack/protection.rb

Enable EscapedParams if passed via settings

---

lib/sinatra/base.rb

I refactored little bit while reading the code. Just some minor changes which I think should be self-explanatory.

minor refactor

---

lib/sinatra/base.rb
test/static_test.rb

This change escapes exception messages on error pages for "not found" and "bad request" errors when serving static content. In particular the message for 404 errors contains the request method and path which are user controlled and should probably be escaped.
This isn't really that exploitable because the path will be URL encoded when being requested by any sane browser, but it seems better to be safe and escape it anyway.
Example error page before the change:
```console
$ curl "https://sinatra.example.com/a<script>"       
GET /a<script>
```
Example after:
```console
$ curl "https://sinatra.example.com/a<script>"       
GET &#x2F;a&lt;script&gt;
```

Add escaping to the static 404 page.

---

lib/sinatra/base.rb

`detect_rack_handler` can be remove becaue it has already been implemented in `Rack::Handler.pick`

remove detect_rack_handler

---

lib/sinatra/base.rb
test/filter_test.rb

Respect content type set in superclass before filter

---

rack-protection/lib/rack/protection/authenticity_token.rb
rack-protection/spec/lib/rack/protection/authenticity_token_spec.rb

Allow the session key for authenticity tokens to be configurable. Instead of`:csrf` it can be configured to match other Rack frameworks like Rails `:_csrf_token`, etc.

Add option to configure token session key

---

sinatra.gemspec

👋 I've recently stumbled across https://github.com/sinatra/sinatra/issues/1578 . Here I've done the changes requested in the issue, that is not including every README file, I've only included the english version in the RDoc documentation.
At my machine time needed to generate documentation decreases drastically:
```bash
❯ gem install sinatra --no-doc
Fetching sinatra-2.1.0.gem
Successfully installed sinatra-2.1.0
1 gem installed
❯ time gem rdoc sinatra
Parsing documentation for sinatra-2.1.0
Installing ri documentation for sinatra-2.1.0
gem rdoc sinatra  262.31s user 1.75s system 97% cpu 4:31.63 total # -----> BEFORE
❯ gem uninstall sinatra
❯ gem specific_install git@github.com:epergo/sinatra.git ep/reduce-rdoc-generation-time
Switched to a new branch 'ep/reduce-rdoc-generation-time' …
```

Reduce RDoc generation time by not including every README

---

sinatra-contrib/lib/sinatra/namespace.rb
sinatra-contrib/spec/namespace_spec.rb

Hi, and thanks for the great projet.
I made this first contribution because it feels like the order is wrong here: If a hash or array is given, the `set(k,v)` line would never be taken into account...
In fact I came accross this issue because using both `sinatra/namespace` and `sinatra-cross_origin` doesn't work for local cross origin. Reproduction be like:
```ruby
namespace "/foo" do
get  "/bar" do
cross_origin allow_origin: "example.com"
send_file "bar"
end
end
```
However, I do think that by design you want to block any global keys to be set from a namespace and do not have enough understanding of how this may work. Hence I'm thinking about fixing this issue directly in the `sinatra-cross_origin` gem. Any input on this one would be much appreciated of course :)

[sinatra-contrib][namespace] Do not raise when key is an enumerable

---

rack-protection/lib/rack/protection/authenticity_token.rb
rack-protection/spec/lib/rack/protection/authenticity_token_spec.rb

Resolves #1616. Makes CSRF tokens more secure (see: https://github.com/rails/rails/pull/22275).
To generate a per form authenticity token, pass the `path` and optionally the form `method` (method defaults to post):
```
Rack::Protection::AuthenticityToken.token(session, path: '/foo')
```

Add support for per form csrf tokens

---

.travis.yml

This PR updates the CI matrix to use latest JRuby, **9.2.16.0**.
[JRuby 9.2.16.0 release blog post](https://www.jruby.org/2021/03/03/jruby-9-2-16-0.html)

CI: Use latest JRuby 9.2.16.0

---

lib/sinatra/base.rb
test/static_test.rb

This change adds additional validation to the requested static file.
cc @namusyaka

Validate expanded path matches public_dir when serving static files

---

lib/sinatra/base.rb
test/delegator_test.rb

When Ruby is upgraded to 3.0, errors result from keyword arguments not being passed correctly through the Delegator `delegate` method. This PR fixes the issue.

Fix Delegator to pass keyword arguments for Ruby 3.0

---

test/delegator_test.rb

- passes on Ruby < 2.7
- passes with warning on Ruby >= 2.7, < 3.0
- fails on Ruby 3.0

Add test for delegation of keyword arguments in `before` method

---

.github/workflows/test.yml

Since forks do not have access to the `SLACK_WEBHOOK` secret, this step would always fail.
---
I tried this by temporarily setting the `SLACK_WEBHOOK` secret om my fork, just to ensure it tries to send upon failures still.

Skip the Slack action if `secrets.SLACK_WEBHOOK` is not set

---

.github/workflows/test.yml

* Disable `fast-fail` so that we can feedback for all versions in the matrix, even if a specific version fails
* Run the test workflow for all branches, this is useful when you want test feedback without having to open a PR

Small CI improvements

---

lib/sinatra/base.rb
test/middleware_test.rb

The added test case would, prior to the fix, fail under Ruby 3.0, with the following error:
```
MiddlewareTest#test_handles_keyword_arguments_0:
ArgumentError: wrong number of arguments (given 2, expected 1)
```
The change itself was inspired by https://github.com/rack/rack/pull/1505

Fix `use` with keyword arguments for Ruby 3.0

---

lib/sinatra/indifferent_hash.rb
test/indifferent_hash_test.rb

This PR adds `#select`, `#reject` and `#compact` methods to `Sinatra::IndifferentHash`.
This allows the following code to work:
```ruby
foo_strings = params[:foo].select {|_, v| v.is_a?(String)}
if foo_strings[:bar]
...
```
Without this PR, the code above would fail because `select` returns a regular `Hash` with string keys.

Add `#select`, `#reject` and `#compact` methods to `Sinatra::IndifferentHash`

---

sinatra.gemspec

This PR removes `test_files` from the gemspec because it is unnecessary.
Sinatra sets an empty array to `test_files` since 987197054525aa5a7f56bfd74895cbbff20dfa4a. The commit omits `test/` directory from published package.
So currently the `test_files` option does nothing.
We have two choices, removing the `test_files`, or adding files under `test/` to `test_files`.
I think the first approach, removing `test_files`, is better. Because `tset_files` is no longer recommended. ref: https://github.com/rubygems/guides/issues/90 https://github.com/rubygems/bundler/pull/3207 
And I guess Sinatra users don't need `test_files` because they had no trouble with empty `test_files`.

Remove unnecessary `test_files` from the gemspec

---

lib/sinatra/base.rb

Fix https://github.com/sinatra/sinatra/issues/1714

Fix memory leaks for proc template

---

lib/sinatra/base.rb
test/mapped_error_test.rb
test/result_test.rb

By extending `Sinatra::Error`, an error class can set the http status code on the response to a value other than 500. This commit fixes issues #1204 and #1518 where an error raised by a third party library that responded to http_status could set the status on the response. Any error outside of Sinatra errors will now always return a 500 status.
This fixes an issue where an exception could leak sensitive data in the message to the browser. Errors that have http_status code 400 or 404 use the message as the body of the response. This is why it is imperative that these errors extend Sinatra::Error so that this is an explicit decision.

Internal Sinatra errors now extend Sinatra::Error

---

lib/sinatra/base.rb
sinatra-contrib/lib/sinatra/namespace.rb

Ruby 2.+ includes a Kernel implementation of `caller_locations`. This implementation differs subtly from the one in Sinatra, causing breakage when another caller tries to use `caller_locations`. Specifically, this blows up with Bootsnap as noted in https://github.com/Shopify/bootsnap/issues/183
This means that it is impossible to correctly use Sinatra in some situations when a Sinatra application is mounted within a Rails project that uses Bootsnap - which is now the default.
This PR removes the hand-rolled implementation of `caller_locations` and instead exposes the Kernel one as a public method. Since Sinatra now mandates Ruby 2.+ there should be no compatibility problems.

Use Kernel#caller_locations (2.x)

---

.github/workflows/test.yml

This PR removes comments cruft from the CI.

chore: Drop auto-generated boilerplate comments from CI configuration file

---

Gemfile
lib/sinatra/base.rb
test/integration_helper.rb
test/integration_test.rb

This PR removes the integration support for Reel.
Reel has been unmaintained since 2016, and we can stop supporting it in the upcoming version of Sinatra.
This PR wants to thank Reel for its service, and let it go.
Fixes #1726

[unstable] fix: Drop reel integration

---

.github/workflows/test.yml
sinatra-contrib/lib/sinatra/config_file.rb

Ruby 3.1 ships with Psych 4.0, which is not evaluating aliases etc. [by default](https://github.com/ruby/psych/pull/487) https://www.ruby-lang.org/en/news/2021/12/25/ruby-3-1-0-released/
This change breaks http://sinatrarb.com/contrib/config_file, where `unsafe_load` introduced in https://github.com/ruby/psych/pull/488 is used now to keep the old behaviour, which is fine as the config file is not user defined.

feat(sinatra): support ruby 3.1

---

CHANGELOG.md

:wave: Hello there! I was having a look att what has been merged since the last release since it's been a while (September 2020) and decided to update the CHANGELOG.
WDYT? Did I miss anything?
---
It's true that we didn't merge anything super important that should be released asap but I think we already have quite some things, maybe is time to cut a release?

Update changelog since last release

---

Gemfile
lib/sinatra/base.rb
test/request_test.rb

This fixes #1739. Now Sinatra returns 400 Bad Request instead of 500.

Handle EOFError raised by Rack and raise BadRequest (and lock Rack version to 2.0 to pass tests)

---

README.ja.md

I Modified 'Using Sessions' section in README.ja.md.
That section currently be of an older README.md version than of #1187.
* Added 3 subsections under the 'セッションの使用' ('Using Sessions') section
* New: 'セッション秘密鍵のセキュリティ' ('Session Secret Security'), 'セッションコンフィグ' ('Session Config')
* Moved: 'セッションミドルウェアの選択' ('Choosing Your Own Session Middleware')
* Renamed 'セッションミドルウェアの選択' to '自分で選んだセッションミドルウェアを使う'
* Replaced 'クッキー' with 'Cookie'
* Added link to '攻撃防御に対する設定' ('Configuring attack protection') in the last sentence of 'セッションの使用' ('Using Sessions') section
* I'm not a crypto expert, so my translation may contain some misunderstanding
* Renaming 'セッションミドルウェアの選択' may not be good

Modify 'Using Sessions' section in README.ja.md to follow #1187

---

README.ja.md

I translated this  commit. https://github.com/sinatra/sinatra/commit/2128dcfb31f0e067bfc8e28afd54b94021caee68#diff-04c6e90faac2675aa89e2176d2eec7d8

Add default_content_type setting in Japanese readme

---

lib/sinatra/base.rb
test/routing_test.rb

Optional named route params overwrite a query param of the same name with nil if not included. Fixes #1666.

Preserve query param value if named route param nil

---

CHANGELOG.md

This PR tags and groups documentation changes to be last in the "changes" section. Perhaps this makes the document easier to scan for "behavior changes".

CHANGELOG v2.2.0: group documentation changes

---

lib/sinatra/base.rb

Follows "The Only Correct Way" from https://eregon.me/blog/2021/02/13/correct-delegation-in-ruby-2-27-3.html
Related to https://github.com/sinatra/sinatra/pull/1670
Fixes https://github.com/sinatra/sinatra/issues/1749

Use `ruby2_keywords` for delegation

---

Gemfile

This PR drops Rubinius lines from Gemfile.
Future PRs can turn the `RUBY_ENGINE` sections into `platforms:` annotations.

Drop Rubinius section from Gemfile

---

Gemfile

This PR attempts to use platforms: in Gemfile.
You can read more about [the Gemfile format of Bundler in the documentation](https://bundler.io/gemfile.html).
See #1751 discussion. 
The tricky part is to omit and include gems, to make them run on JRuby. **Update**: I was patient, and added enough platforms annotations that it was possible to `bundle install` locally for me.

Use Bundler "platforms" in Gemfile

---

Gemfile
test/rabl_test.rb

This change is a follow-up to e168cb5d49d76bbfb9d719c610bccef69747b62b
Thanks to eregon for noting that :mri is distinct from :ruby.
With this change, Truffleruby stands a better chance of installing the right gems in the Gemfile.
- We use `:ruby` as a `platforms:` argument. That allows Truffleruby to also install these gems, along with their C extensions.
- In addition, this PR upgrades ActiveSupport to `~> 6.1`, to get to a version of the `tzinfo` gem compatible with concurrent-ruby. This avoids a runtime exception thrown in Truffleruby in the test suite.
**Update**: I ran into "RablTest needs more core_ext stuff loaded!" so I found https://api.rubyonrails.org/classes/Array.html#method-i-extract_options-21 and loaded that for that test.

Gemfile: Use :ruby to denote platform-with-C-exts

---

Rakefile

This is related to work happening for https://github.com/sinatra/sinatra/pull/1751#issuecomment-1050947044
Removing these two settings deals with this Truffleruby warning:
> [To redirect Truffle log output to a file use one of the following options:
> * '--log.file=<path>' if the option is passed using a guest language launcher.
> * '-Dpolyglot.log.file=<path>' if the option is passed using the host Java launcher.
> * Configure logging using the polyglot embedding API.]
> [ruby] WARNING: Encoding.find('locale') is US-ASCII, this often indicates that the system locale is not set properly. Set LANG=C and LC_ALL=C to suppress this warning (but some things might break).
>

Stop setting LANG=C and not removing LC_TYPE ENV vars; that disrupt Truffleruby

---

Gemfile
test/haml_test.rb

We have lots of warnings for `haml` in our test suite <details>
<summary>Like this</summary>
```
/home/runner/work/sinatra/sinatra/vendor/bundle/jruby/2.6.0/gems/tilt-2.0.10/lib/tilt/haml.rb:77: warning: Haml::Engine#precompiled_method_return_value at /home/runner/.rubies/jruby-9.3.3.0/lib/ruby/stdlib/forwardable.rb:158 forwarding to private method Haml::Compiler#precompiled_method_return_value
/home/runner/work/sinatra/sinatra/vendor/bundle/jruby/2.6.0/gems/tilt-2.0.10/lib/tilt/haml.rb:77: warning: Haml::Engine#precompiled_method_return_value at /home/runner/.rubies/jruby-9.3.3.0/lib/ruby/stdlib/forwardable.rb:158 forwarding to private method Haml::Compiler#precompiled_method_return_value
/home/runner/work/sinatra/sinatra/vendor/bundle/jruby/2.6.0/gems/tilt-2.0.10/lib/tilt/haml.rb:77: …
```

Update haml and slim dependencies in tests

---

Rakefile

The `Rakefile` appears to add the project directory to the load path which doesn't seem correct.

Avoid adding project directory to the load path for tests

---

README.de.md
README.es.md
README.fr.md
README.hu.md
README.ja.md
README.ko.md
README.malayalam.md
README.md
README.pl.md
README.pt-br.md
README.pt-pt.md
README.ru.md
README.zh.md

Ruby doesn't ship with Webrick anymore, so users will need to install their own webserver.
Fixes #1754

Update "Getting Started" docs

---

.github/workflows/test.yml

This is an uncontroversial update: the GH Actions has been updated.

CI: Use actions/checkout@v3

---

rack-protection/lib/rack/protection/authenticity_token.rb

Instead, replaced it with a snippet on how to provide compatibility.
Fixes #1778

authenticity token: removed reference of compatibility with rack_csrf

---

lib/sinatra/base.rb
test/static_test.rb

This is the fix for issues created by #1566. See there for more details.

Do not let NotFound exception leak path info.

---

rack-protection/lib/rack/protection/authenticity_token.rb

Currently, the user can send in a hash or array parameter instead of string, which in turn throws a NoMethodError exception in Base64.urlsafe_decode64.
This fix makes sure that only string tokens are accepted and other data are not passed any further.

Make sure the authenticity token is a string.

---

Gemfile
lib/sinatra/base.rb
test/integration_helper.rb
test/integration_test.rb
test/settings_test.rb

Update to https://github.com/sinatra/sinatra/pull/1677 which can be closed after merging this, all tests passing locally. LMK if any further changes are needed.

Falcon integration

---

Gemfile
rack-protection/Gemfile
rack-protection/rack-protection.gemspec
sinatra-contrib/Gemfile
sinatra-contrib/lib/sinatra/test_helpers.rb
sinatra-contrib/sinatra-contrib.gemspec
sinatra.gemspec

Allow versions greater (and equals) than 2.0 for the `rack-test` gem. The only change needed was to remove the `build_rack_test_session` in test_helper because it uses the deprecated `rack_mock_session` which calls `build_rack_test_session` again creating an infinite loop

Use latest version of rack-test

---

sinatra-contrib/lib/sinatra/contrib/version.rb
sinatra-contrib/lib/sinatra/reloader.rb
sinatra-contrib/spec/reloader_spec.rb

* Make `after_reload` run only if paths were updated.
* Pass the actual reloaded paths to the `after_reload` blocks.
Hi Sinatra folks. I've used Sinatra for many years, and it's the best. But this is the first time I've tried `after_reload` under the `Sinatra::Reloader` module.
I found that it was running my `after_reload` block _every_ time my modular app ran, even when no files changed. This seems to have fixed it.
For your reference, here's the actual code in my app that uses it:
```ruby
configure :development do
register Sinatra::Reloader # http://sinatrarb.com/contrib/reloader
ApiConfig.extra_watch_files.each { |file| also_reload file }
puts "+ Reloader: Watching #{ApiConfig.extra_watch_files.size} extra files."
after_reload do |paths|
puts "+ Reloader: Reloaded paths: #{paths}"
end …
```

Improve `after_reload` issues

---

.github/workflows/test.yml

No longer needed since https://github.com/ruby/setup-ruby/issues/358

Remove workaround

---

rack-protection/lib/rack/protection/escaped_params.rb

The documentation for [Rack::Protection::EscapedParams](https://github.com/sinatra/sinatra/blob/bc8d0c8f1ae92717ec553e3f9469952719cdc38c/rack-protection/lib/rack/protection/escaped_params.rb) currently states:
>  Calls html_safe on the escaped strings if defined, to avoid double-escaping in Rails.
However, a quick search shows no mentions of `html_safe` in the Sinatra code repository nor in https://github.com/rack/rack (which is where [`Rack::Utils.escape_html`](https://github.com/rack/rack/blob/856934f8252d414378e9c17a56573db50c5784a5/lib/rack/utils.rb#L186-L189), the default escaping method, is defined).
Testing this with Rails, the behavior also confirms `html_safe` is not set on escaped strings:
```ruby
Loading development environment (Rails 7.0.1)                     
3.1.0 :001 > …
```

Update documentation for Rack::Protection::EscapedParams

---

CHANGELOG.md
README.md
sinatra-contrib/README.md
sinatra-contrib/lib/sinatra/reloader.rb

Document the deprecation of Sinatra Reloader and suggest alternatives.
Closes #1534 and #1381.

Deprecate Sinatra Reloader

---

sinatra-contrib/Gemfile
sinatra-contrib/spec/content_for_spec.rb

In recent version [2.16.1](https://github.com/k0kubun/hamlit/compare/v2.16.0...v2.16.1#diff-420695a198614966ed3845b1d3ab3165415f651c30ca6e271339cf0f850952f1R9) of Hamlit, the class `Hamlit::Compiler::ScriptCompiler` was modified to receive a second parameter in its constructor, however the gem `hamlit-block` which uses aforementioned gem wasn't updated so it still tries to instantiate a new `ScriptCompiler` class with only [one parameter](https://github.com/hamlit/hamlit-block/blob/master/lib/hamlit/block/compiler.rb#L15)
We should move to support hamlit version 3 so here I've fixed the version to be the last one that was working, 2.15.2

Fix hamlit version

---

Gemfile
sinatra-contrib/Gemfile

Fix JRuby CI error. Should be able to remove once JRuby is updated.

Pin jar-dependencies to 0.4.1

---

rack-protection/lib/rack-protection.rb

In order to keep compat with earlier files, this wrapper file is needed.
See https://github.com/omniauth/omniauth/issues/1089
This is a reaction to https://github.com/sinatra/sinatra/pull/1537#issuecomment-1257647560 - thanks @mvz !

fix: add back a rack-protection.rb file

---

.github/workflows/test.yml
Gemfile
rack-protection/Gemfile

This PR changes the configured branch name for a GitHub Actions matrix element that runs our test suite with the latest development code of Rack.
Rack has changed the name of the default branch, to `main`. This PR now reflects the current default branch of that repository.
Issue manifests in CI as:
> Revision master does not exist in the repository
> https://github.com/rack/rack.git. Maybe you misspelled it?
After this change, we get this, which is more of what we want from a CI job like this (which is exploring the next major version):
> 
> Fetching https://github.com/rack/rack.git
> Fetching https://github.com/rack/rack-test.git
> Fetching gem metadata from https://rubygems.org/.......
> Resolving dependencies...
> Bundler could not find compatible versions for gem "rack":
>   In …

CI: Refer to rack/rack default branch as 'main'

---

.rubocop.yml
lib/sinatra/base.rb

Revert to using stderr.puts for start up message

---

CHANGELOG.md

This is a small change to the file; there may be more changes in the release that may need to go in the file, but this fixes the issue that there was a date missing.

CHANGELOG: mark the 3.0.0 release date

---

sinatra-contrib/lib/sinatra/capture.rb
sinatra-contrib/lib/sinatra/content_for.rb
sinatra-contrib/sinatra-contrib.gemspec
sinatra-contrib/spec/content_for/passes_values.haml

Use Haml::Buffer only if it is defined. Resolves #1816.

Support Haml 6

---

README.md

It appears Travis is no longer used as the latest build is older than a year ago. Pointing the link to GitHub CI may help here.

Update CI URL in README

---

test/integration_helper.rb

Hello.
TruffleRuby doesn't support `Fiber.set_scheduler` method so it will be great not to run tests (temporary) that involve this method call on TruffleRuby.
Right now only integration tests with Falcon rely on this method so here in this PR Falcon server is skipped in tests if `Fiber.set_scheduler` is not implemented.
Does it make sense?

Don't run integration tests on Falcon against TruffleRuby

---

lib/sinatra/base.rb
test/helpers_test.rb

according the multipart form data spec in WHATWG living standard.
Ref: https://html.spec.whatwg.org/#multipart-form-data
cc @jkowens

escape filename in the Content-Disposition header

---

README.md

See https://github.com/rtomayko/tilt/blob/a8b10cae56606ba657eeb9a06f1077155909c425/lib/tilt.rb#L22
The first argument is the Tilt template engine class, the second argument is the extension.

fix Tilt.register argument order in readme

---

.github/workflows/test.yml

Needed to be able to install psych >=5.
Need to do it before setup-ruby runs as that runs `bundle install`.
Related to:
- https://github.com/ruby/psych/pull/541
- https://github.com/ruby/setup-ruby/issues/409
- https://github.com/actions/runner-images/issues/6725
Yes, libyaml-dev will be added to GitHub runner images (this week they say) but opening this PR just in case anyone encounters failing builds. I don't think it hurts having this in the repo even after libyaml-dev have been added to the images.
Added some blank lines to make the workflow easier to read.

Install `libyaml-dev` in CI

---

lib/sinatra/base.rb

Without this the app file will be set to zeitwerk/kernel.rb instead of the actual app file since that's what caller_files.first will return.
Fixes https://github.com/sinatra/sinatra/issues/1826

Add Zeitwerk to CALLERS_TO_IGNORE

---

Gemfile
test/haml_test.rb

In Haml 6, = escapes the results of the Ruby expression by default. If you want that to be a nested  template it needs to be called with !=.
Also, attr_wrapper is no longer a valid option.

Tests against Haml 6

---

test/integration_helper.rb

Fix skipping integration tests with falcon on TruffleRuby.
Skip tests with falcon only for TruffleRuby. Ruby versions < 3.0 don't support `Fiber.set_scheduler` but are still supported by falcon. So we need to run specs with falcon on Ruby versions < 3.0 but skip it for TruffleRuby.
Related PR - https://github.com/sinatra/sinatra/pull/1839

Skip falcon only for TruffleRuby

---

.github/workflows/test.yml
sinatra-contrib/Gemfile

- Include gemfile in job name
To be able to tell the difference without opening each job.
- Avoid exact versions in sinatra-contrib/Gemfile
Introduced in a1722ca
Nokogiri 1.13.6 can't be installed on Ruby 3.2:
https://github.com/sinatra/sinatra/actions/runs/3793184348/jobs/6450054080#step:6:14

CI: add jobs testing with Puma 5 and Ruby 3.2

---

.github/workflows/test.yml
Gemfile
gems/rack-v3.rb
rack-protection/Gemfile
sinatra-contrib/Gemfile
sinatra.gemspec
test/server_test.rb

This reverts commit 2ccd0dc29dc699c40a71ef6c1c8702668cc73d1b.
It doesn't make sense to have this in master when it is not working. CI will install Rack 3 and fail jobs. We don't know if we break something for Rack 2 now.
@jkowens please consider this

Revert "Allow running with Rack 3. (#1811)"

---

.github/workflows/test.yml

See https://github.com/sinatra/sinatra/actions/runs/4138714331/jobs/7155450583#step:5:639
Failure was
1) Failure:
IntegrationTest#test_with_webrick_does_not_generate_warnings_0 [/home/runner/work/sinatra/sinatra/test/integration_test.rb:56]:

CI: allow JRuby and head versions to fail

---

examples/chat.rb
lib/sinatra/base.rb
test/integration/app.rb
test/integration_async_helper.rb
test/integration_helper.rb
test/streaming_test.rb

@ioquatix I also tried to test this with Falcon as well, but it didn't seem to work. Does Falcon buffer the response?
This is somewhat modeled after streaming in Roda: https://github.com/jeremyevans/roda/blob/c919ac9c7e88f159f8c6185b0bdb5a9311e24d93/lib/roda/plugins/streaming.rb#L143

Add support to keep open streaming connections with Puma

---

lib/sinatra/base.rb

The alias was deprecated: https://github.com/rack/rack/pull/1811

`Rack::File` -> `Rack::Files`

---

.github/workflows/test.yml
Gemfile
rack-protection/Gemfile
sinatra-contrib/Gemfile

Adds [Tilt](https://rubygems.org/gems/tilt) to the CI matrix. It now resides at https://github.com/jeremyevans/tilt
Changes `latest` to `head` because "latest" sounds a lot like "latest release" but we mean using the main/master branch of the repo of the dependency we test with. Matches `ruby-head`.

CI: handle dependencies the same way, add Tilt to the matrix

---

.gitignore
test/integration/app.rb
test/integration_helper.rb
test/integration_test.rb

2nd commit fixes timing issue with Puma, adds 0.05 second to sleep, small changes to asserts and time calc
Two commits:
1. [.gitignore - add Bundler items](https://github.com/sinatra/sinatra/commit/963e92e7a8b9bd8bbe93bf6b17d6746d364fd4af)
2. [[CI] Fix up integration stream test](https://github.com/sinatra/sinatra/commit/1e4bb7727452c48a07a5f4cbf4e0fe702a3abe37)

[CI] Fix up integration stream test for Puma

---

lib/sinatra/base.rb

Rescue `RuntimeError` when trying to use `SecureRandom`

---

.github/workflows/test.yml
sinatra-contrib/Gemfile

Needed to run with Tilt 2.1.0 in CI  until https://github.com/slim-template/slim/pull/910 is part of a Slim release.

Use slim HEAD branch

---

README.md
lib/sinatra/base.rb
rack-protection/spec/spec_helper.rb
sinatra-contrib/README.md
sinatra-contrib/lib/sinatra/test_helpers.rb
sinatra-contrib/spec/spec_helper.rb

- Rack changed default branch to "main"
- rubydoc.info redirects to https://

Update broken links in docs

---

sinatra-contrib/Gemfile

2.6.x is very old, https://rubygems.org/gems/liquid/versions
2.6.3 - July 23, 2015 (45.5 KB)
Found these traces in history:
- https://github.com/sinatra/sinatra/commit/741677743cbebe2cca5992b4dd767eec89350c30
- https://github.com/sinatra/sinatra-contrib/commit/2dc03c879a858a418cfc3697fe7afd0b53e0f766

Use latest liquid release in sinatra-contrib CI

---

.github/workflows/test.yml

`~> 6.0` will install latest Puma release, that's what `stable` do too
Better we add this job once Puma 7 exist.

CI: remove redundant Puma job

---

.github/workflows/test.yml

Some examples
Multiple failed jobs
A single failed job
If the previous run failed, but now it passes
When the previous run failed, but still not fixed

Add action-discord notifications to main

---

rack-protection/README.md

This added whitespace doesn't change anything in GitHub's README output but it fixes the generated HTML for https://sinatrarb.com/protection/ (the issue occurs when regenerating the HTML for the page and is correct on the currently-live version of the page).

Tiny Rack::Protection README formatting fix

---

README.md

See https://github.com/sinatra/sinatra/issues/1548
The behavior of `raise_errors` isn't well-documented.
When `true`:
* The application will raise errors only for errors that do not have explicit handlers
* The application will raise errors despite any explicit catch-all handler, e.g. `error { ... }` or `error Exception { ... }`
As discussed in https://github.com/sinatra/sinatra/issues/1548, it seems that a future version of sinatra could afford a change to this behavior, since it is somewhat inconsistent, and some options are discussed therein.
In the short-term, we are proposing an update to the documentation.
Once we decide on the final language here, we can open up an accompanying PR for https://github.com/sinatra/sinatra.github.com/ since it [also …

Issue 1548: Describe raise_errors better in README

---

lib/sinatra/base.rb
sinatra-contrib/lib/sinatra/namespace.rb
test/sinatra_test.rb

Tilt::Cache is deprecated and will be removed.  Copy the implementation currently used as Sinatra::TemplateCache, so Sinatra is not affected by the deprecation and removal of Tilt::Cache.
Fixes #1884

Remove use of Tilt::Cache

---

.github/workflows/test.yml
Gemfile
README.md
lib/sinatra/base.rb
sinatra-contrib/lib/sinatra/engine_tracking.rb
sinatra-contrib/lib/sinatra/namespace.rb
sinatra-contrib/lib/sinatra/respond_with.rb
sinatra-contrib/sinatra-contrib.gemspec
sinatra-contrib/spec/respond_with/not_html.sass
test/sass_test.rb
test/scss_test.rb
test/views/error.sass
test/views/hello.sass
test/views/hello.scss

This PR adds support for sass back via [sass-embedded](https://github.com/ntkme/sass-embedded-host-ruby) (backed by currently maintained official [dart-sass-embedded](https://github.com/sass/dart-sass-embedded)).
It requires `tilt>=2.0.11`, which is the first version that introduced support for sass-embedded.

Add sass support via sass-embedded

---

Gemfile

traces 0.10.0 started to use Ruby 2.7 syntax without specifying required Ruby version https://github.com/socketry/traces/pull/8#discussion_r1237988182
async-http 0.60.2 added traces 0.10.0 as dependency https://github.com/socketry/async-http/pull/124/files#r1237988899
(falcon depends on async-http)

Make CI pass on Ruby 2.6

---

README.md
examples/lifecycle_events.rb
lib/sinatra/base.rb
test/server_test.rb

This PR adds lifecycle events to Sinatra. Related issue: #1184

Add start and stop callbacks

---

test/server_test.rb

The old MiniTest constant isn't defined out-of-the-box since minitest v5.19.0:
- https://github.com/minitest/minitest/commit/a2c6c18570f6f0a1bf6af70fe3b6d9599a13fdd6
- https://github.com/minitest/minitest/commit/96a9972916bc0102eb755e77d22dd51f1c69a309
- https://github.com/minitest/minitest/blob/ed88d196bc5dde30d48026ef7b338997b640e799/lib/minitest/unit.rb

Use `Minitest` instead of `MiniTest`

---

.github/workflows/test.yml

Noticed that the action failed due to being rate limited by GitHub, and it is not much we can do about that right now, the action needs to be updated to take the GitHub token as an input, not try to read it from ENV, I think:
https://github.com/zzak/action-discord/blob/2edb53786004cf3d17fa27315d671f3dcbc2b269/main.rb#L22
It doesn't matter much if this workflow fails, more important that CI looks green IMHO.

CI: Always allow `notify` job to fail

---

CHANGELOG.md

Takes care of the missing link to PR 1911:

Fix PR link in changelog

---

lib/sinatra/indifferent_hash.rb
test/indifferent_hash_test.rb

The method `Hash#except` [was added in Ruby 3.0](https://github.com/ruby/ruby/commit/82ca8c73034b0a522fd2970ea39edfcd801955fe) so it would be nice that calling `except` in a `Sinatra::IndifferntHash` supported the indifferent access that the latter provides – right now, calling `except(:a)` on `Sinatra::IndifferntHash[a: :a]` would not filter the `a` key.
This commits adds indifferent access support to except so that it will exclude the passed key independently if the key is passed as a `String` or `Symbol`.

feature: add `except` to `IndifferntHash`

---

lib/sinatra/base.rb

We already do for the 500 image, see 238eedeb52dbbf688d561751d9dd5ad79c59c6ff
Close #1939

Use relative URL for the 404 image

---

README.md

This PR updates the old dead link for slim template website to its new github pages website.

Update link for slim template

---

rack-protection/rack-protection.gemspec

This PR adds `base64` to rack-protection.gemspec because `base64` will not be part of the default gems since Ruby 3.4.0.
Resolves https://github.com/sinatra/sinatra/issues/1937

Add `base64` to rack-protection runtime dependencies

---

Gemfile
rack-protection/Gemfile
rack-protection/rack-protection.gemspec
sinatra-contrib/Gemfile
sinatra-contrib/sinatra-contrib.gemspec
sinatra.gemspec

See the commits.
Close https://github.com/sinatra/sinatra/issues/1918

Use `Gemfile`s to manage dev/test dependencies + cleanup

---

Gemfile

Due to https://github.com/socketry/async-io/pull/72 released in async-io 1.37.0
We will need this fix as long as we want to test Falcon in Ruby 2.6, as the "fix" in async-io will be to raise the min Ruby version: https://github.com/socketry/async-io/issues/74
Fail can be seen at https://github.com/sinatra/sinatra/actions/runs/6836408460/job/18591270458#step:5:19

CI: use `async-io` 1.36.1 in Ruby 2.6 builds

---

Gemfile

async-io >= 1.38.0 should work with Ruby 2.6 again.
This reverts 734df89affd8de6350195bb7692848da2e3a7ec1.

Use latest `async-io`

---

README.md

Related to: https://github.com/sinatra/sinatra/pull/1956
Remove reference to Rainbows (and the example) in the multithreading section of the Readme but keep the section where we explain Sinatra is thread safe and should work out of the box.

Update multithreading section to remove Rainbows reference

---

sinatra-contrib/lib/sinatra/contrib.rb
sinatra-contrib/lib/sinatra/haml_helpers.rb
sinatra-contrib/spec/haml_helpers_spec.rb

Brings back three helpers from Haml 5:
https://github.com/haml/haml/blob/v5.2.2/lib/haml/helpers.rb#L294-L357

Add `Sinatra::HamlHelpers` to sinatra-contrib

---

Gemfile

We had many more failures in https://github.com/sinatra/sinatra/actions/runs/7087638977 due to the json gem 2.7.0 (https://github.com/flori/json/issues/553), but those was fixed with json 2.7.1 (https://github.com/flori/json/pull/554).

Fix CI issues due to markaby 0.9.1

---

README.md

Remove any references to the `sysrandom` gem from the README. The gem has been archived because it is no longer needed. Ruby 2.5 introduced the fix that the gem previously handled.
Fixes #1963.

Remove references `sysrandom` gem

---

Gemfile
rack-protection/Gemfile

It is not needed.
Including it hides real problems: https://github.com/sinatra/sinatra/pull/1857#discussion_r1434926762

CI: remove sinatra from rack-protection bundle

---

Gemfile
rack-protection/Gemfile
sinatra-contrib/Gemfile

This comes from https://github.com/sinatra/sinatra/pull/1801 and maybe it was a reason back then but I don't see any now.
This just makes things simpler, for example, the Docker Ruby images based on Alpine does not come with git.

CI: use latest rack-test release, not trunk

---

.github/workflows/release.yml
RELEASING.md
Rakefile

- https://blog.rubygems.org/2023/12/14/trusted-publishing.html
- https://guides.rubygems.org/trusted-publishing/
This makes it possible for anyone who can push a tag to sinatra/sinatra (or access the "Run workflow" button in the Actions UI) to cut a release.
I think that's OK, the overlap between https://rubygems.org/gems/sinatra/owners and https://github.com/orgs/sinatra/teams/team-sinatra is already great. It gives two more people access to cut releases.
Close https://github.com/sinatra/sinatra/issues/1920

Add workflow for Trusted Publishing to RubyGems

---

.github/workflows/test.yml

This makes much more sense because it is common to use rack-protection without sinatra.
Ref: https://github.com/sinatra/sinatra/pull/1971#discussion_r1437616734

CI: move rack-protection to its own job

---

.github/workflows/test.yml
Gemfile
lib/sinatra/base.rb
sinatra-contrib/lib/sinatra/runner.rb
test/integration/simple_app.rb
test/integration/zeitwerk_app.rb
test/integration_start_helper.rb
test/integration_start_test.rb

Close https://github.com/sinatra/sinatra/issues/1973

Ruby 3.3 + Bundler 2.5 compatibility

---

sinatra-contrib/lib/sinatra/runner.rb

This reverts commit 0e43702c3feeeed3495aa4590c0cecd04204d4d7.
This wasn't needed for anything more than making the tests fail faster when I was developing. It could be seen as a breaking change, so let's just back it out.

Revert "Shorter `Sinatra::Runner` timeout"

---

.github/workflows/release.yml

If tags are pushed to the fork.
Guard like this can be seen in https://github.com/segiddins/rubygems-await/blob/06fa16da619d334c0a2ff8e1f821bbbf1622a42e/.github/workflows/push_gem.yml#L10

Avoid running release workflow in forks

---

Gemfile
test/integration_start_helper.rb

Use the awesome pull request by eregon: https://github.com/enkessler/childprocess/pull/175 that uses native Process.spawn on all platforms
JVM rubies can't use the default fork+exec approach in childprocess, so we fall back to CHILDPROCESS_POSIX_SPAWN, but that is not available on aarch64 (me using Docker on Apple silicon). Annoying when debugging tests.
(This should still work even after the PR is merged and the branch removed)

CI: use improved version of `childprocess` gem

---

Gemfile

Just makes the dev life easier.
References: https://github.com/protocolbuffers/protobuf/issues/11935, https://github.com/jruby/jruby/issues/8062

CI: skip testing `sass-embedded` on JVM rubies on aarch64

---

lib/sinatra/indifferent_hash.rb
test/indifferent_hash_test.rb

See these links for background:
- https://github.com/sinatra/sinatra/pull/1951
- https://github.com/sinatra/sinatra/issues/1948
Before
> Sinatra::IndifferentHash.new(a: 1)[:b]
=> {"a"=>1}
After
> Sinatra::IndifferentHash.new(a: 1)[:b]
=> {:a=>1}
Close #1953

Remove the `IndifferentHash` initializer

---

README.md
rack-protection/README.md
rack-protection/lib/rack/protection.rb
rack-protection/spec/lib/rack/protection/protection_spec.rb

Also remove the very old[1] `does not include ...` comment.
Fighting the test I had to change made me realize just how much the order of middlewares matters. Not very intuitive 😞. Maybe someday someone will get to https://github.com/sinatra/sinatra/issues/1659
Close #1930
1: https://github.com/sinatra/sinatra/commit/0985552f331b572d72ad96ce06f03816da57340c

Make `session_hijacking` an optional protection

---

.github/workflows/test.yml
Gemfile
rack-protection/Gemfile

See the commits.
Prep for https://github.com/sinatra/sinatra/issues/1945.

CI: test `rack-session` head, test only latest JRuby

---

.github/workflows/test.yml

Due to https://github.com/sinatra/sinatra/issues/2007

CI: allow `truffleruby` to fail

---

test/indifferent_hash_test.rb

Fixes <https://github.com/sinatra/sinatra/issues/2026>.
```
sinatra/test/indifferent_hash_test.rb:29: warning: Calling Hash.new with keyword arguments is deprecated and will be removed in Ruby 3.4; use Hash.new({ key: value }) instead
```

Fix warning about Hash construction.

---

Gemfile
rack-protection/rack-protection.gemspec

```
rack-protection/lib/rack/protection/base.rb:6: warning: logger was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.5.0. Add logger to your Gemfile or gemspec.
test/rabl_test.rb:5: warning: ostruct was loaded from the standard library, but will no longer be part of the default gems since Ruby 3.5.0. Add ostruct to your Gemfile or gemspec.
```

Declare missing dependencies for Ruby 3.5

---

.github/workflows/test.yml
Gemfile
sinatra-contrib/lib/sinatra/capture.rb
sinatra-contrib/lib/sinatra/link_header.rb
sinatra-contrib/lib/sinatra/runner.rb
test/integration_helper.rb
test/routing_test.rb

Ever since Ruby 2.3 it has been possible to enable frozen string literals globally via `RUBYOPT`, and it is scheduled to be the default in Ruby 4.

Fix compatibility with `--enable-frozen-string-literal`

---

Gemfile

Not sure what's going on, but we need green CI.
See https://github.com/sinatra/sinatra/issues/2047

CI: Avoid Zeitwerk 2.7.0+ for testes, for now

---

.github/workflows/test.yml

Due to https://github.com/jruby/ruby-maven/issues/12

CI: unset `RUBYOPT` for JRuby jobs

---

lib/sinatra/base.rb

Avoid this upcoming warning:
ruby 3.4.0dev (2024-11-07T00:17:16Z master 342455e56f) +PRISM [x86_64-linux]
-e:1: warning: URI::RFC3986_PARSER.unescape is obsoleted. Use URI::RFC2396_PARSER.unescape explicitly.
Close https://github.com/sinatra/sinatra/issues/2057

Address `URI` depreciation

---

lib/sinatra/indifferent_hash.rb
test/indifferent_hash_test.rb

To keep consistency, make sure that `Sinatra::IndifferentHash#except` returns an instance of `Sinatra::IndifferentHash` instead of `Hash`. 
Before
```ruby
> h = Sinatra::IndifferentHash[{a: 1, b: 2}]
=> {"a"=>1, "b"=>2}
> h.class
=> Sinatra::IndifferentHash
> h.except(:b)
=> {"a"=>1}
> h.except(:b).class
=> Hash
```
After
```ruby
> h = Sinatra::IndifferentHash[{a: 1, b: 2}]
=> {"a"=>1, "b"=>2}
> h.class
=> Sinatra::IndifferentHash
> h.except(:b)
=> {"a"=>1}
> h.except(:b).class
=> Sinatra::IndifferentHash
```

Return an instance of Sinatra::IndifferentHash when calling #except

---

README.md
lib/sinatra/base.rb
rack-protection/README.md
rack-protection/lib/rack/protection.rb
rack-protection/lib/rack/protection/base.rb
rack-protection/lib/rack/protection/host_authorization.rb
rack-protection/spec/lib/rack/protection/host_authorization_spec.rb
rack-protection/spec/lib/rack/protection/protection_spec.rb
rack-protection/spec/support/spec_helpers.rb
test/helpers_test.rb
test/host_authorization_test.rb
test/request_test.rb

The Sinatra project received a security report with the following details:
> Title: Reliance on Untrusted Inputs in a Security Decision
> CWE ID: CWE-807
> CVE ID: CVE-2024-21510
> Credit: t0rchwo0d
> Description: The sinatra package is vulnerable to Reliance on Untrusted
> Inputs in a Security Decision via the `X-Forwarded-Host (XFH)` header.
> When making a request to a method with redirect applied, it is possible
> to trigger an Open Redirect Attack by inserting an arbitrary address
> into this header. If used for caching purposes, such as with servers
> like Nginx, or as a reverse proxy, without handling the
> `X-Forwarded-Host` header, attackers can potentially exploit Cache
> Poisoning or Routing-based SSRF.
The vulnerable code was introduced in fae7c011. Sinatra can not know …

Add `HostAuthorization` rack-protection middleware

---

README.md

See what https://github.com/sinatra/sinatra.github.com/commit/cc1cadf088268dcd2b219b24d6d03ff80d8cf526 did
I hope this fixes it

Multiple `<dd>` tags breaks the website HTML

---

Gemfile
lib/sinatra/base.rb
test/integration_helper.rb
test/integration_test.rb
test/settings_test.rb

4a55850 was a bit aggressive, it should not have dropped the "out of the box" experience for Sinatra and WEBrick when you have the required gems installed.

Restore WEBrick support

---

lib/sinatra/base.rb
test/base_test.rb

Here we only ensure that `=~` is applicable by calling `to_s` before using it.
Close https://github.com/sinatra/sinatra/issues/2077

Avoid crash for integer values in `content_type` parameters

---

lib/sinatra/base.rb
test/helpers_test.rb

This commit ensures that all parameters of `Content-Type` are separated with commas (`,`) instead of semicolons (`;`).
[RFC 7231](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.5) says:
```
Content-Type = media-type
Media types are defined in [Section 3.1.1.1](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1).
An example of the field is
Content-Type: text/html; charset=ISO-8859-4
```
[RFC 7231 3.1.1.1](https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.1) says:
```
Media types define both a data format and various processing models:
how to process that data in accordance with each context in which it
is received.
media-type = type "/" subtype *( OWS ";" OWS parameter )
type       = token
subtype    = token
The type/subtype MAY be followed by parameters …
```

Fix malformed Content-Type headers

---

README.md

The Readme has already been updated to require rackup and puma as hard dependencies (line 21). No need to also then recommend to install Puma on line 37.

Remove duplicate mention of installing puma from README.md

---

sinatra.gemspec

It is already set to true for sinatra-contrib and rack-protection, happened in https://github.com/sinatra/sinatra/pull/1537

Set `rubygems_mfa_required` for the `sinatra` gem

---

README.md
lib/sinatra/base.rb
test/static_test.rb

This PR implements recent feature request related to static file responses. It introduces a new configuration setting, `:static_headers`, which allows developers to define custom headers that will be applied to all static file responses served by `static!` -method.
Fixes #2088
Sinatra serves static files directly via `static!`, bypassing filters and middleware. This makes it so that there is no good ways to add headers like `Access-Control-Allow-Origin`, which are often needed for CORS access (e.g., when using fonts or images on canvas).

Add :static_headers setting for custom headers in static file responses

---

test/routing_test.rb

This is a temporary fix for https://github.com/sinatra/sinatra/issues/2113 as https://github.com/rack/rack/pull/2316 is merged.

Skip broken tests.
