sinatra/sinatra

README.hu.md
=> Fix grammar

README.pt-br.md
Few content missing translation yet
=> Update Portuguese (Brazil) README

README.pt-br.md
This PR is pt-br version for #993
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/sinatra/sinatra/996)
=> Add pt-br documentation for Multithreaded modes

lib/sinatra/show_exceptions.rb
I did some refactoring in the code, while I was studying sinatra:
* Remove unnecessary comment.
* Fix indentation.
* Increase readability.
=> Some refactoring on ShowExceptions class.

README.fr.md
I made an attempt at adding documentation about using Sinatra in multi-threaded mode, however my French is conversational, not technical, and I expect that I have made numerous typos, as well as missing the mark on technical expressions. See #941
/cc @karouf @michelc @robin850 Would you mind suggesting improvements before this gets merged?
=> Add documentation in French about multi-threading.

.travis.yml, sinatra.gemspec
https://travis-ci.org/sinatra/sinatra/jobs/67398284#L155
/cc #1009 #1010 @TrevorBramble @kytrinyx @rkh
=> Bump Rack to 1.5.x, but not 1.6 since it doesn't work on 1.8.7:

README.fr.md
Hello,
I never really maintained this translation since I first created it, so I decided to proceed to a full review and fix as many things as possible. Each commit contains only one kind of modification (typos, grammar...) just in case they need to be filtered.
Cheers,
mig
=> French readme

README.ja.md
This PR is Japanese version for #993
=> Add documentation in Japanese about multi-threading.

README.es.md
This is a direct translation of #993 (Issue #941).
=> Document how to start a multi-threaded server (Spanish)

README.ko.md
Original change can see in this link: [23c2e19...f749860](https://github.com/sinatra/sinatra/compare/23c2e19...f749860#diff-04c6e90faac2675aa89e2176d2eec7d8) 
@yous review please.
=> Update Korean translation to f749860

README.ru.md
https://github.com/sinatra/sinatra/commit/ec7d1abb8cbf21df7a640b4f36f399fde37b2b07#commitcomment-13742099
thanks @texpert! :tada: :+1: :star2:
=> Update russian documentation

CONTRIBUTING.md
Fixing a few typos, improving the formatting and other improvements.
=> Minor fixes and improvements to CONTRIBUTING.md

AUTHORS.md
Thanks everyone :heart: :heart: :heart:
=> Move @kytrinyx to alumni section of authors list

AUTHORS.md
:tada: :heart: :balloon: :clap:
=> Add Kashyap to the AUTHORS.md file

lib/sinatra/base.rb
=> Revert "extended Helper with Forwardable for delegation"

README.zh.md
The original Chinese translation was rather outdated. This pull request aims at updating it to comply with the current English version (README.md). Many sentences are also rephrased to improve readability.
=> Update and polish the Chinese translation (README.zh.md)

.travis.yml, Gemfile
https://travis-ci.org/kares/sinatra/builds/106434071
=> a green jruby build

sinatra-contrib/Gemfile, sinatra-contrib/lib/sinatra/reloader.rb, sinatra-contrib/spec/reloader_spec.rb
```ruby
also_reload '/path/to/some/file'
dont_reload '/path/to/other/file'
after_reload do
puts 'reloaded'
end
```
=> Add .after_reload to Sinatra::Reloader

README.ja.md
I fixed README.ja.md
- Add some of sections which are not have been translated.
- Delete unnecessary beak lines.
- Unify some of text there was a difference of expression.
=> Fix README.ja.md[ci skip]

README.hu.md
based on [the English version](https://github.com/sinatra/sinatra/blob/master/README.md#multi-threading)
=> Add docs in Hungarian about multi-threading

sinatra-contrib/Gemfile
therubyracer (0.12.3) has been released 🎉 
https://rubygems.org/gems/therubyracer/versions/0.12.3
This release version includes https://github.com/cowboyd/therubyracer/pull/413.
Thanks!
=> Use therubyracer (0.12.3)

sinatra-contrib/lib/sinatra/test_helpers.rb, sinatra-contrib/sinatra-contrib.gemspec
- Extracted from #1208
- Partial fix of #1207
=> Make Rack::Test a development dependency

README.md
=> Use SVG Travis badge over PNG

README.de.md, README.md
Don't pull yet, I'll post further translations and then squash the commits into one or two commits.
I'll post my updates to the German README here as it progresses. There have been quite a few changes throughout the months.
Wer mithelfen möchte, kann dies gerne tun, das Dokument lässt sich ja problemlos aufteilen.
=> Update German README

rack-protection/lib/rack/protection/json_csrf.rb, rack-protection/spec/lib/rack/protection/json_csrf_spec.rb
=> Add allow_if option to bypass json csrf protection

CHANGELOG.md
fixes #1276 
Update CHANGELOG.md till date. This should be good for release :shipit:
=> [issue-1276] update CHANGELOG.md for 2.0.0 release

rack-protection/README.md
This PR changes one of the READMEs to **use SVG** for its build status **badge icon**. For clarity! ✨
=> README: Use snazzy SVG for build badge

CHANGELOG.md
Much as I'd like to I can't take credit for this change. @singpolyma wrote the code, I just rebased it :)
=> Re-credit changelog entry

lib/sinatra/base.rb
Align the comment.
This is the first time I have submitted an open source project, hoping to have a good start~
=> Remove a space in comment

test/asciidoctor_test.rb, test/builder_test.rb, test/coffee_test.rb, test/creole_test.rb, test/erb_test.rb, test/haml_test.rb, test/less_test.rb, test/liquid_test.rb, test/markaby_test.rb, test/mediawiki_test.rb, test/nokogiri_test.rb, test/rabl_test.rb, test/radius_test.rb, test/rdoc_test.rb, test/sass_test.rb, test/scss_test.rb, test/slim_test.rb, test/stylus_test.rb, test/textile_test.rb, test/wlang_test.rb, test/yajl_test.rb
This is my first help on Sinatra. Test still passing after this
=> deleting unnecesary to_s

README.md
I've added some links on readme
=> Adding links on readme

README.zh.md
1. Update docs about how to use Mustermann options to match routes.
2. Update docs about Session Secret Security.
Thanks!
=> Update docs about Session  and Routes

sinatra-contrib/lib/sinatra/namespace.rb, sinatra-contrib/spec/namespace_spec.rb
Fixes #1310 
@aren55555 @mencargo @zzak Could you confirm this?
=> avoid prefix duplication

README.md
I added a description because I was having trouble without being reflected when changing the code.
=> Notes on code change

CHANGELOG.md
=> CHANGELOG line about v1.4.8

README.es.md
Translation to Spain of Sinatra's current readme :tada: #1249
=> Update README.es.md according to last version of README.md

AUTHORS.md
=> add myself to current team

CHANGELOG.md
=> update changelog about CVE-2018-7212

sinatra-contrib/README.md
=> [Carry #1307] sinatra-contrib README: Fix links

lib/sinatra/base.rb, test/helpers_test.rb, test/response_test.rb
close https://github.com/sinatra/sinatra/issues/1397
=> Remove status code 205 from drop body responses

sinatra-contrib/lib/sinatra/capture.rb, sinatra-contrib/lib/sinatra/contrib.rb, sinatra-contrib/lib/sinatra/contrib/setup.rb, sinatra-contrib/lib/sinatra/cookies.rb, sinatra-contrib/lib/sinatra/extension.rb, sinatra-contrib/lib/sinatra/namespace.rb, sinatra-contrib/lib/sinatra/streaming.rb, sinatra-contrib/sinatra-contrib.gemspec, sinatra-contrib/spec/streaming_spec.rb
* Remove backports
* Work around Object#try and String#underscore
=> Sinatra::Contrib dependency updates. Fixes #1207

sinatra-contrib/lib/sinatra/capture.rb, sinatra-contrib/lib/sinatra/contrib.rb, sinatra-contrib/lib/sinatra/contrib/setup.rb, sinatra-contrib/lib/sinatra/cookies.rb, sinatra-contrib/lib/sinatra/extension.rb, sinatra-contrib/lib/sinatra/namespace.rb, sinatra-contrib/lib/sinatra/streaming.rb, sinatra-contrib/sinatra-contrib.gemspec, sinatra-contrib/spec/streaming_spec.rb
=> Revert "Sinatra::Contrib dependency updates. Fixes #1207"

Gemfile
see https://github.com/sinatra/sinatra/pull/1405#issuecomment-385150329
Updates: https://github.com/sinatra/sinatra/issues/1423
Ref: https://github.com/rails/rails/issues/14643
=> lock activesupport to ~> 5.1.6

lib/sinatra/base.rb
=> escape invalid query params, fixes #1428

CHANGELOG.md
This is a PR on top of the PR #1437, adding Issue links to the Markdown.
=> CHANGELOG.md v2.0.2 links

README.malayalam.md
- malayalam is a language used in Indian state Kerala
=> Translating readme to malayalam. Half of the portion is done

Gemfile, README.ja.md, README.md, lib/sinatra/base.rb, sinatra-contrib/README.md, sinatra-contrib/lib/sinatra/capture.rb, sinatra-contrib/lib/sinatra/content_for.rb, sinatra-contrib/lib/sinatra/engine_tracking.rb, sinatra-contrib/lib/sinatra/respond_with.rb, sinatra-contrib/sinatra-contrib.gemspec, sinatra-contrib/spec/capture_spec.rb, sinatra-contrib/spec/content_for_spec.rb, test/erb_test.rb
I added docs, testing to support [erubi](https://github.com/jeremyevans/erubi). I can write only Japanese and English, so I updated only them. This is related to #1487 .
=> Fix #1487 update test and docs to support erubi

README.de.md, README.fr.md, README.ja.md, README.ko.md, README.ru.md, README.zh.md
ref: https://github.com/sinatra/sinatra/pull/1469
=> Update Rack::Protection link in Readme.*.md

lib/sinatra/base.rb, lib/sinatra/main.rb
This reverts commit 3ae2e01a0fa88596fedf2a0b62079c97aa4d5bcc.
ref #1547
=> Revert "Fix issue setting environment from command line option"

lib/sinatra/main.rb
This won't break the backward-compatibility, and probably the original issue can be fixed.
@jkowens Can you review this? 
ref #1553 #1547
=> correct fix for #1547

sinatra-contrib/lib/sinatra/config_file.rb, sinatra-contrib/spec/config_file/key_value.yaml, sinatra-contrib/spec/config_file_spec.rb
Allow .yaml files
Related with #1563
=> Fix/allow yaml files for Issue #1563

README.pt-br.md
fix #1249 
PT-BR translation update. I made some corrections and additions. If anything is wrong, please, let me know. 
Can you do a quick review @Klockner?
=> 1249 update readme translations

rack-protection/spec/lib/rack/protection/cookie_tossing_spec.rb, test/static_test.rb
Rack added support for Multi-part ranges and apparently changed the format of cookie expires timestamp format to match specs.
=> Fix failing tests

lib/sinatra/version.rb, rack-protection/lib/rack/protection/version.rb, sinatra-contrib/lib/sinatra/contrib/version.rb
=> Fix issue with passed routes and provides

README.fr.md, README.md
- A few typos and wrong spelling here and there
=> Update French readme

.travis.yml
This PR updates the CI configuration to use latest patch releases in each version.
=> CI: Use latest Ruby versions

rack-protection/lib/rack/protection/authenticity_token.rb
Credit goes to @jeremyevans for this performance improvement on the Rails project.
See: https://github.com/rails/rails/pull/32931
=> Improve xor_byte_strings performance

.travis.yml, CHANGELOG.md, lib/sinatra/base.rb
=> add a changelog for v2.1

rack-protection/lib/rack/protection/http_origin.rb, rack-protection/spec/lib/rack/protection/http_origin_spec.rb
=> Fix broken origin_whitelist option #1641

README.md
=> Document when dump_errors is enabled

README.pl.md
This PR is polish version for #993
=> Add polish documentation for Multithreaded modes

CHANGELOG.md
See https://github.com/sinatra/sinatra/issues/1744
=> Add CHANGELOG for v3.0.0 (Unreleased)

.github/workflows/test.yml, test/integration_helper.rb
another attempt at https://github.com/sinatra/sinatra/pull/1751
to catch regressions such as https://github.com/sinatra/sinatra/issues/1749
let me know if there's anything else needed
=> CI: let's roll tests with JRuby

README.de.md, README.ja.md, README.ko.md, README.malayalam.md, README.md, README.pl.md, README.pt-br.md, README.ru.md, README.zh.md
Updates to fix and remove a few error-prone examples in the README.
=> #1667 - Custom Route Matchers documentation updated

.github/workflows/test.yml, Gemfile
=> Run CI job against `rack` main branch

.github/workflows/test.yml, Gemfile, test/settings_test.rb
Fixes #1799 and #1798.
cc @dentarg
=> Fixes for TruffleRuby

README.pt-br.md
I made some changes to the Portuguese BR, over the days I will correct more.
=> correction in Portuguese Brazil

README.md
=> Inline Templates: need to use `!=` with Haml 6

README.md
=> Link to discord

.github/workflows/CODEOWNERS
I've setup branch protection to avoid force pushes and deletions to the main branch
=> Require an approval from a maintainer before merge

test/integration_async_helper.rb, test/integration_helper.rb, test/integration_test.rb
=> Start servers for async tests before running tests

CHANGELOG.md
The changes worth mentioning from https://github.com/sinatra/sinatra/compare/v3.0.5...055087c274e181c2dad77a2b140e7190028b7cfb
=> Changes between Dec 22, 2022 and Feb 26, 2023

CONTRIBUTING.md, MAINTENANCE.md, README.md, rack-protection/rack-protection.gemspec, sinatra-contrib/README.md, sinatra-contrib/Rakefile, sinatra-contrib/sinatra-contrib.gemspec, sinatra.gemspec
Related to https://github.com/sinatra/sinatra/issues/1696
=> Rename `master` branch to `main`

test/sinatra_test.rb
=> Revert "Test build failure on main"

examples/stream.ru, lib/sinatra/base.rb
=> Make Puma the default server

.github/workflows/test.yml
https://github.com/zzak/action-discord/releases/tag/v6
=> Use zzak/action-discord@v6

.github/workflows/test.yml
Bump actions/checkout while we're here.
=> CI: ensure up-to-date apt package index files

.github/workflows/test.yml, rack-protection/spec/lib/rack/protection/authenticity_token_spec.rb, rack-protection/spec/lib/rack/protection/xss_header_spec.rb
Close https://github.com/sinatra/sinatra/issues/1983
=> Address warnings seen in rack-protection specs

README.md
Close https://github.com/sinatra/sinatra/issues/2003
=> README: the minimal example needs `rackup`

.github/workflows/test.yml, lib/sinatra/base.rb, lib/sinatra/middleware/logger.rb, rack-protection/spec/lib/rack/protection/cookie_tossing_spec.rb, sinatra.gemspec
TODO
Close https://github.com/sinatra/sinatra/issues/2019
Close https://github.com/sinatra/sinatra/issues/2017
Close https://github.com/sinatra/sinatra/issues/2018
Close https://github.com/sinatra/sinatra/issues/2014
Close https://github.com/sinatra/sinatra/pull/2029 (cherry-picked to this branch)
=> Rack 3.1 compatibility

sinatra-contrib/lib/sinatra/haml_helpers.rb
`helpers` is the one we want to use here: https://github.com/sinatra/sinatra/blob/973c936319af9132d7ab2f60985e359d0c75c93e/lib/sinatra/base.rb#L1552-L1557
=> Fix `Sinatra::HamlHelpers` docs

.github/workflows/test.yml, Gemfile
See the commits.
Close https://github.com/sinatra/sinatra/issues/2051
=> Resolve CI issues

.github/workflows/test.yml, Gemfile, lib/sinatra/base.rb
Changed in 2.7.0, see https://github.com/fxn/zeitwerk/commit/8f37a65ee5c18f0fa3e1bf28283e8ee4b1b9b39e
Close https://github.com/sinatra/sinatra/issues/2047
=> Support Zeitwerk 2.7.0+

Gemfile, README.md, lib/sinatra/base.rb, rack-protection/lib/rack/protection/authenticity_token.rb, test/integration_helper.rb, test/integration_start_test.rb, test/integration_test.rb, test/settings_test.rb
=> Handle `rackup` 2.2.0 fallout

rack-protection/spec/lib/rack/protection/host_authorization_spec.rb
Due to https://github.com/rack/rack/pull/2298
See also
- https://github.com/rack/rack/issues/2295
- https://github.com/rails/rails/pull/54613
=> CI: don't use `Rack::Lint` on invalid hostname

CHANGELOG.md, lib/sinatra/base.rb, test/routing_test.rb
=> `PATH_INFO` can never be empty.
